version: '3.8'
services:
  mariadb:
    image: mariadb:latest
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_DATABASE
    volumes:
      - mariadb-data:/var/lib/mysql
    ports:
      - '3306:3306'

volumes:
  mariadb-data:
