INSERT INTO `CarType` (`car_type_name`,`car_type_code`) VALUES ('승용','S')
INSERT INTO `CarType` (`car_type_code`,`car_type_name`) VALUES ('J','SUV')


INSERT INTO `Car` (`car_code`,`car_type_id`,`car_name`,`car_image_path`) VALUES ('CN12',1,'더 뉴 아반떼','/images/car/CN12.png')
INSERT INTO `Car` (`car_name`,`car_code`,`car_image_path`,`car_type_id`) VALUES ('투싼','NX05','/images/car/NX05.png',2)


INSERT INTO `Engine` (`engine_code`,`engine_name`) VALUES ('R','가솔린 1.6')
INSERT INTO `Engine` (`engine_code`,`engine_name`) VALUES ('L','LPG 1.6')
INSERT INTO `Engine` (`engine_name`,`engine_code`) VALUES ('디젤','D')
INSERT INTO `Engine` (`engine_code`,`engine_name`) VALUES ('T','1.6 가솔린 터보')


INSERT INTO `Mission` (`mission_name`,`mission_code`) VALUES ('A/T','T')
INSERT INTO `Mission` (`mission_code`,`mission_name`) VALUES ('A,T','A/T')
INSERT INTO `Mission` (`mission_code`,`mission_name`) VALUES ('D,H','DCT')


INSERT INTO `Drive` (`drive_code`,`drive_name`) VALUES ('D,T','2WD')
INSERT INTO `Drive` (`drive_name`,`drive_code`) VALUES ('4WD','A,H')


INSERT INTO `Trim` (`trim_code`,`trim_name`) VALUES ('B','Smart')
INSERT INTO `Trim` (`trim_name`,`trim_code`) VALUES ('Modern','D')
INSERT INTO `Trim` (`trim_name`,`trim_code`) VALUES ('Premium','C')
INSERT INTO `Trim` (`trim_code`,`trim_name`) VALUES ('P','Inspiration')


INSERT INTO `CarEngine` (`engine_id`,`car_id`) VALUES (1,1)
INSERT INTO `CarEngine` (`engine_id`,`car_id`) VALUES (2,1)
INSERT INTO `CarEngine` (`engine_id`,`car_id`) VALUES (3,2)
INSERT INTO `CarEngine` (`engine_id`,`car_id`) VALUES (4,2)


INSERT INTO `CarMission` (`car_id`,`mission_id`) VALUES (1,1)
INSERT INTO `CarMission` (`mission_id`,`car_id`) VALUES (2,2)
INSERT INTO `CarMission` (`mission_id`,`car_id`) VALUES (3,2)


INSERT INTO `CarDrive` (`drive_id`,`car_id`) VALUES (1,2)
INSERT INTO `CarDrive` (`car_id`,`drive_id`) VALUES (2,2)


INSERT INTO `CarTrim` (`car_id`,`trim_id`) VALUES (1,1)
INSERT INTO `CarTrim` (`car_id`,`trim_id`) VALUES (1,2)
INSERT INTO `CarTrim` (`trim_id`,`car_id`) VALUES (4,1)
INSERT INTO `CarTrim` (`car_id`,`trim_id`) VALUES (2,2)
INSERT INTO `CarTrim` (`trim_id`,`car_id`) VALUES (3,2)
INSERT INTO `CarTrim` (`car_id`,`trim_id`) VALUES (2,4)


INSERT INTO `CarModel` (`model_image_path`,`engine_id`,`model_price`,`mission_id`,`drive_id`,`trim_id`,`model_code`,`car_id`,`model_name`) VALUES ('/images/model/CN12-smart.png',1,19750000,1,null,1,'CNJS4RBT3',1,'더 뉴 아반떼 가솔린 1.6 Smart A/T')
INSERT INTO `CarModel` (`model_image_path`,`car_id`,`trim_id`,`mission_id`,`model_name`,`model_code`,`drive_id`,`model_price`,`engine_id`) VALUES ('/images/model/CN12-modern.png',1,2,1,'더 뉴 아반떼 가솔린 1.6 Modern A/T','CNJS4RDT3',null,22730000,1)
INSERT INTO `CarModel` (`model_price`,`engine_id`,`trim_id`,`model_name`,`model_code`,`drive_id`,`mission_id`,`car_id`,`model_image_path`) VALUES (26910000,1,4,'더 뉴 아반떼 가솔린 1.6 Inspiration A/T','CNJS4RGT3',null,1,1,'/images/model/CN12-inspiration.png')
INSERT INTO `CarModel` (`engine_id`,`model_code`,`car_id`,`model_image_path`,`drive_id`,`model_name`,`model_price`,`mission_id`,`trim_id`) VALUES (2,'CNJS4LBT3',1,'/images/model/CN12-smart.png',null,'더 뉴 아반떼 LPG 1.6 Smart A/T',21150000,1,1)
INSERT INTO `CarModel` (`trim_id`,`drive_id`,`car_id`,`model_price`,`mission_id`,`model_image_path`,`engine_id`,`model_name`,`model_code`) VALUES (2,null,1,24120000,1,'/images/model/CN12-modern.png',2,'더 뉴 아반떼 LPG 1.6 Modern A/T','CNJS4LDT3')
INSERT INTO `CarModel` (`drive_id`,`car_id`,`model_name`,`mission_id`,`trim_id`,`model_price`,`model_code`,`engine_id`,`model_image_path`) VALUES (null,1,'더 뉴 아반떼 LPG 1.6 Inspiration A/T',1,4,28180000,'CNJS4LGT3',2,'/images/model/CN12-inspiration.png')
INSERT INTO `CarModel` (`trim_id`,`model_image_path`,`mission_id`,`drive_id`,`model_name`,`model_code`,`car_id`,`engine_id`,`model_price`) VALUES (2,'/images/model/NX05-modern.png',2,1,'투싼 디젤 Modern 2WD A/T','NXJJ5DDT2',2,3,28190000)
INSERT INTO `CarModel` (`model_price`,`mission_id`,`car_id`,`engine_id`,`trim_id`,`model_image_path`,`drive_id`,`model_code`,`model_name`) VALUES (31100000,2,2,3,3,'/images/model/NX05-premium.png',1,'NXJJ5DCT2','투싼 디젤 Premium 2WD A/T')
INSERT INTO `CarModel` (`mission_id`,`model_image_path`,`model_name`,`engine_id`,`trim_id`,`car_id`,`drive_id`,`model_code`,`model_price`) VALUES (2,'/images/model/NX05-inspiration.png','투싼 디젤 Inspiration 2WD A/T',3,4,2,1,'NXJJ5DPT2',34780000)
INSERT INTO `CarModel` (`model_image_path`,`trim_id`,`model_code`,`model_name`,`engine_id`,`model_price`,`car_id`,`mission_id`,`drive_id`) VALUES ('/images/model/NX05-modern.png',2,'NXJJ5DDA2','투싼 디젤 Modern 4WD A/T',3,30420000,2,2,2)
INSERT INTO `CarModel` (`trim_id`,`model_code`,`model_name`,`mission_id`,`model_image_path`,`drive_id`,`model_price`,`engine_id`,`car_id`) VALUES (3,'NXJJ5DCA2','투싼 디젤 Premium 4WD A/T',2,'/images/model/NX05-premium.png',2,33330000,3,2)
INSERT INTO `CarModel` (`model_code`,`drive_id`,`model_name`,`model_image_path`,`car_id`,`mission_id`,`engine_id`,`model_price`,`trim_id`) VALUES ('NXJJ5DPA2',2,'투싼 디젤 Inspiration 4WD A/T','/images/model/NX05-inspiration.png',2,2,3,37010000,4)
INSERT INTO `CarModel` (`car_id`,`model_code`,`model_price`,`mission_id`,`drive_id`,`model_image_path`,`trim_id`,`model_name`,`engine_id`) VALUES (2,'NXJJ5TDD2',26030000,3,1,'/images/model/NX05-modern.png',2,'투싼 1.6 가솔린 터보 Modern 2WD DCT',4)
INSERT INTO `CarModel` (`model_name`,`car_id`,`mission_id`,`engine_id`,`model_code`,`drive_id`,`model_price`,`model_image_path`,`trim_id`) VALUES ('투싼 1.6 가솔린 터보 Premium 2WD DCT',2,3,4,'NXJJ5TCD2',1,28940000,'/images/model/NX05-premium.png',3)
INSERT INTO `CarModel` (`model_image_path`,`model_price`,`mission_id`,`drive_id`,`model_code`,`model_name`,`trim_id`,`engine_id`,`car_id`) VALUES ('/images/model/NX05-inspiration.png',32620000,3,1,'NXJJ5TPD2','투싼 1.6 가솔린 터보 Inspiration 2WD DCT',4,4,2)
INSERT INTO `CarModel` (`car_id`,`mission_id`,`model_name`,`model_image_path`,`model_code`,`model_price`,`drive_id`,`engine_id`,`trim_id`) VALUES (2,3,'투싼 1.6 가솔린 터보 Modern 4WD DCT','/images/model/NX05-modern.png','NXJJ5TDH2',28010000,2,4,2)
INSERT INTO `CarModel` (`model_name`,`model_code`,`model_price`,`mission_id`,`model_image_path`,`engine_id`,`drive_id`,`car_id`,`trim_id`) VALUES ('투싼 1.6 가솔린 터보 Premium 4WD DCT','NXJJ5TCH2',30920000,3,'/images/model/NX05-premium.png',4,2,2,3)
INSERT INTO `CarModel` (`model_price`,`trim_id`,`mission_id`,`model_code`,`drive_id`,`model_image_path`,`car_id`,`engine_id`,`model_name`) VALUES (34600000,4,3,'NXJJ5TPH2',2,'/images/model/NX05-inspiration.png',2,4,'투싼 1.6 가솔린 터보 Inspiration 4WD DCT')


INSERT INTO `IntColor` (`car_id`,`int_color_code`,`int_color_image_path`,`int_color_name`) VALUES (1,'NNB','/images/interior-color/NNB.png','블랙모노톤')
INSERT INTO `IntColor` (`car_id`,`int_color_name`,`int_color_image_path`,`int_color_code`) VALUES (1,'세이지그린','/images/interior-color/SSS.png','SSS')
INSERT INTO `IntColor` (`int_color_image_path`,`int_color_code`,`car_id`,`int_color_name`) VALUES ('/images/interior-color/VHC.png','VHC',1,'캐쉬미어 베이지')
INSERT INTO `IntColor` (`int_color_image_path`,`int_color_code`,`int_color_name`,`car_id`) VALUES ('/images/interior-color/I34.png','I34','블랙모노톤',2)
INSERT INTO `IntColor` (`int_color_name`,`int_color_code`,`int_color_image_path`,`car_id`) VALUES ('블랙 모노톤(가죽 시트)','I35','/images/interior-color/I35.png',2)
INSERT INTO `IntColor` (`int_color_name`,`int_color_code`,`int_color_image_path`,`car_id`) VALUES ('블랙/그레이 투톤(그레이 가죽시트)','I36','/images/interior-color/I36.png',2)
INSERT INTO `IntColor` (`int_color_name`,`car_id`,`int_color_image_path`,`int_color_code`) VALUES ('네이비 원톤(인디고 모노톤)',2,'/images/interior-color/I37.png','I37')
INSERT INTO `IntColor` (`car_id`,`int_color_name`,`int_color_code`,`int_color_image_path`) VALUES (2,'블랙모노톤(레드스티치)','I38','/images/interior-color/I38.png')
INSERT INTO `IntColor` (`car_id`,`int_color_name`,`int_color_image_path`,`int_color_code`) VALUES (2,'블랙 / 브라운 투톤(브라운 가죽시트)','/images/interior-color/PRF.png','PRF')


INSERT INTO `ExtColor` (`ext_color_name`,`ext_color_image_path`,`car_id`,`ext_color_code`) VALUES ('아마존 그레이 메탈릭','/images/exterior-color/A5G.png',1,'A5G')
INSERT INTO `ExtColor` (`ext_color_image_path`,`car_id`,`ext_color_code`,`ext_color_name`) VALUES ('/images/exterior-color/PE2.png',1,'PE2','에코트로닉 그레이펄')
INSERT INTO `ExtColor` (`car_id`,`ext_color_name`,`ext_color_code`,`ext_color_image_path`) VALUES (1,'플루이드 그레이 메탈릭','M6T','/images/exterior-color/M6T.png')
INSERT INTO `ExtColor` (`ext_color_name`,`car_id`,`ext_color_code`,`ext_color_image_path`) VALUES ('메타블루펄',1,'PM2','/images/exterior-color/PM2.png')
INSERT INTO `ExtColor` (`ext_color_image_path`,`car_id`,`ext_color_code`,`ext_color_name`) VALUES ('/images/exterior-color/YP5.png',1,'YP5','인텐스 블루 펄')
INSERT INTO `ExtColor` (`car_id`,`ext_color_name`,`ext_color_image_path`,`ext_color_code`) VALUES (1,'아틀라스 화이트','/images/exterior-color/SAW.png','SAW')
INSERT INTO `ExtColor` (`ext_color_image_path`,`ext_color_code`,`car_id`,`ext_color_name`) VALUES ('/images/exterior-color/R2P.png','R2P',1,'얼티메이트 레드 메탈릭')
INSERT INTO `ExtColor` (`ext_color_code`,`ext_color_image_path`,`car_id`,`ext_color_name`) VALUES ('A2B','/images/exterior-color/A2B.png',1,'어비스블랙펄')
INSERT INTO `ExtColor` (`car_id`,`ext_color_image_path`,`ext_color_code`,`ext_color_name`) VALUES (1,'/images/exterior-color/C5G.png','C5G','사이버 그레이 메탈릭')
INSERT INTO `ExtColor` (`car_id`,`ext_color_image_path`,`ext_color_name`,`ext_color_code`) VALUES (2,'/images/exterior-color/B6S.png','실키 브론즈 메탈릭','B6S')
INSERT INTO `ExtColor` (`car_id`,`ext_color_name`,`ext_color_code`,`ext_color_image_path`) VALUES (2,'쉬머링 실버 메탈릭','R2T','/images/exterior-color/R2T.png')
INSERT INTO `ExtColor` (`ext_color_image_path`,`car_id`,`ext_color_code`,`ext_color_name`) VALUES ('/images/exterior-color/TW3.png',2,'TW3','크리미 화이트 펄')
INSERT INTO `ExtColor` (`car_id`,`ext_color_image_path`,`ext_color_name`,`ext_color_code`) VALUES (2,'/images/exterior-color/A5G.png','아마존 그레이 메탈릭','A5G')
INSERT INTO `ExtColor` (`car_id`,`ext_color_image_path`,`ext_color_code`,`ext_color_name`) VALUES (2,'/images/exterior-color/R4G.png','R4G','티탄 그레이 메탈릭')
INSERT INTO `ExtColor` (`ext_color_code`,`ext_color_name`,`ext_color_image_path`,`car_id`) VALUES ('PS8','오션 인디고 펄','/images/exterior-color/PS8.png',2)
INSERT INTO `ExtColor` (`car_id`,`ext_color_name`,`ext_color_image_path`,`ext_color_code`) VALUES (2,'팬텀 블랙 펄','/images/exterior-color/TCM.png','TCM')
INSERT INTO `ExtColor` (`ext_color_name`,`ext_color_image_path`,`car_id`,`ext_color_code`) VALUES ('티타늄 그레이 매트','/images/exterior-color/Y3G.png',2,'Y3G')


INSERT INTO `IntExtColor` (`ext_color_id`,`int_color_id`) VALUES (1,1)
INSERT INTO `IntExtColor` (`int_color_id`,`ext_color_id`) VALUES (1,2)
INSERT INTO `IntExtColor` (`ext_color_id`,`int_color_id`) VALUES (3,1)
INSERT INTO `IntExtColor` (`int_color_id`,`ext_color_id`) VALUES (1,4)
INSERT INTO `IntExtColor` (`ext_color_id`,`int_color_id`) VALUES (5,1)
INSERT INTO `IntExtColor` (`int_color_id`,`ext_color_id`) VALUES (1,6)
INSERT INTO `IntExtColor` (`ext_color_id`,`int_color_id`) VALUES (8,1)
INSERT INTO `IntExtColor` (`int_color_id`,`ext_color_id`) VALUES (1,9)
INSERT INTO `IntExtColor` (`int_color_id`,`ext_color_id`) VALUES (1,7)
INSERT INTO `IntExtColor` (`int_color_id`,`ext_color_id`) VALUES (2,1)
INSERT INTO `IntExtColor` (`int_color_id`,`ext_color_id`) VALUES (2,2)
INSERT INTO `IntExtColor` (`ext_color_id`,`int_color_id`) VALUES (3,2)
INSERT INTO `IntExtColor` (`ext_color_id`,`int_color_id`) VALUES (6,2)
INSERT INTO `IntExtColor` (`ext_color_id`,`int_color_id`) VALUES (8,2)
INSERT INTO `IntExtColor` (`ext_color_id`,`int_color_id`) VALUES (9,2)
INSERT INTO `IntExtColor` (`ext_color_id`,`int_color_id`) VALUES (1,3)
INSERT INTO `IntExtColor` (`int_color_id`,`ext_color_id`) VALUES (3,2)
INSERT INTO `IntExtColor` (`ext_color_id`,`int_color_id`) VALUES (3,3)
INSERT INTO `IntExtColor` (`int_color_id`,`ext_color_id`) VALUES (3,4)
INSERT INTO `IntExtColor` (`ext_color_id`,`int_color_id`) VALUES (5,3)
INSERT INTO `IntExtColor` (`ext_color_id`,`int_color_id`) VALUES (6,3)
INSERT INTO `IntExtColor` (`ext_color_id`,`int_color_id`) VALUES (8,3)
INSERT INTO `IntExtColor` (`ext_color_id`,`int_color_id`) VALUES (9,3)
INSERT INTO `IntExtColor` (`int_color_id`,`ext_color_id`) VALUES (4,10)
INSERT INTO `IntExtColor` (`int_color_id`,`ext_color_id`) VALUES (4,11)
INSERT INTO `IntExtColor` (`int_color_id`,`ext_color_id`) VALUES (4,12)
INSERT INTO `IntExtColor` (`ext_color_id`,`int_color_id`) VALUES (13,4)
INSERT INTO `IntExtColor` (`ext_color_id`,`int_color_id`) VALUES (14,4)
INSERT INTO `IntExtColor` (`ext_color_id`,`int_color_id`) VALUES (15,4)
INSERT INTO `IntExtColor` (`ext_color_id`,`int_color_id`) VALUES (16,4)
INSERT INTO `IntExtColor` (`ext_color_id`,`int_color_id`) VALUES (10,5)
INSERT INTO `IntExtColor` (`ext_color_id`,`int_color_id`) VALUES (11,5)
INSERT INTO `IntExtColor` (`ext_color_id`,`int_color_id`) VALUES (12,5)
INSERT INTO `IntExtColor` (`ext_color_id`,`int_color_id`) VALUES (13,5)
INSERT INTO `IntExtColor` (`int_color_id`,`ext_color_id`) VALUES (5,14)
INSERT INTO `IntExtColor` (`ext_color_id`,`int_color_id`) VALUES (15,5)
INSERT INTO `IntExtColor` (`int_color_id`,`ext_color_id`) VALUES (5,16)
INSERT INTO `IntExtColor` (`int_color_id`,`ext_color_id`) VALUES (6,10)
INSERT INTO `IntExtColor` (`ext_color_id`,`int_color_id`) VALUES (11,6)
INSERT INTO `IntExtColor` (`ext_color_id`,`int_color_id`) VALUES (12,6)
INSERT INTO `IntExtColor` (`ext_color_id`,`int_color_id`) VALUES (13,6)
INSERT INTO `IntExtColor` (`int_color_id`,`ext_color_id`) VALUES (6,14)
INSERT INTO `IntExtColor` (`int_color_id`,`ext_color_id`) VALUES (6,15)
INSERT INTO `IntExtColor` (`ext_color_id`,`int_color_id`) VALUES (16,6)
INSERT INTO `IntExtColor` (`int_color_id`,`ext_color_id`) VALUES (7,11)
INSERT INTO `IntExtColor` (`int_color_id`,`ext_color_id`) VALUES (7,12)
INSERT INTO `IntExtColor` (`ext_color_id`,`int_color_id`) VALUES (14,7)
INSERT INTO `IntExtColor` (`int_color_id`,`ext_color_id`) VALUES (7,15)
INSERT INTO `IntExtColor` (`int_color_id`,`ext_color_id`) VALUES (7,16)
INSERT INTO `IntExtColor` (`int_color_id`,`ext_color_id`) VALUES (9,10)
INSERT INTO `IntExtColor` (`int_color_id`,`ext_color_id`) VALUES (9,11)
INSERT INTO `IntExtColor` (`int_color_id`,`ext_color_id`) VALUES (9,12)
INSERT INTO `IntExtColor` (`int_color_id`,`ext_color_id`) VALUES (9,13)
INSERT INTO `IntExtColor` (`int_color_id`,`ext_color_id`) VALUES (9,14)
INSERT INTO `IntExtColor` (`int_color_id`,`ext_color_id`) VALUES (9,16)


INSERT INTO `TrimIntColor` (`trim_id`,`int_color_id`) VALUES (1,1)
INSERT INTO `TrimIntColor` (`trim_id`,`int_color_id`) VALUES (2,1)
INSERT INTO `TrimIntColor` (`trim_id`,`int_color_id`) VALUES (2,2)
INSERT INTO `TrimIntColor` (`trim_id`,`int_color_id`) VALUES (4,1)
INSERT INTO `TrimIntColor` (`int_color_id`,`trim_id`) VALUES (2,4)
INSERT INTO `TrimIntColor` (`int_color_id`,`trim_id`) VALUES (3,4)
INSERT INTO `TrimIntColor` (`trim_id`,`int_color_id`) VALUES (2,4)
INSERT INTO `TrimIntColor` (`int_color_id`,`trim_id`) VALUES (4,3)
INSERT INTO `TrimIntColor` (`int_color_id`,`trim_id`) VALUES (5,3)
INSERT INTO `TrimIntColor` (`int_color_id`,`trim_id`) VALUES (6,3)
INSERT INTO `TrimIntColor` (`trim_id`,`int_color_id`) VALUES (4,5)
INSERT INTO `TrimIntColor` (`int_color_id`,`trim_id`) VALUES (6,4)
INSERT INTO `TrimIntColor` (`trim_id`,`int_color_id`) VALUES (4,7)
INSERT INTO `TrimIntColor` (`trim_id`,`int_color_id`) VALUES (4,9)


INSERT INTO `OptionType` (`option_type_name`) VALUES ('detail')
INSERT INTO `OptionType` (`option_type_name`) VALUES ('hga')
INSERT INTO `OptionType` (`option_type_name`) VALUES ('performance')


INSERT INTO `Option` (`option_price`,`option_image_path`,`option_type_id`,`option_code`,`option_name`) VALUES (690000,'/images/option/CV1.png',1,'CV1','컨비니언스 Ⅰ')
INSERT INTO `Option` (`option_type_id`,`option_image_path`,`option_code`,`option_name`,`option_price`) VALUES (1,'/images/option/IFN.png','IFN','인포테인먼트 내비',790000)
INSERT INTO `Option` (`option_price`,`option_code`,`option_name`,`option_image_path`,`option_type_id`) VALUES (250000,'HER','하이패스+ECM 룸미러','/images/option/HER.png',1)
INSERT INTO `Option` (`option_type_id`,`option_image_path`,`option_name`,`option_code`,`option_price`) VALUES (1,'/images/option/HS3.png','현대 스마트센스 Ⅲ','HS3',690000)
INSERT INTO `Option` (`option_type_id`,`option_code`,`option_price`,`option_name`,`option_image_path`) VALUES (1,'AT1',490000,'17인치 알로이 휠 & 타이어 Ⅰ','/images/option/AT1.png')
INSERT INTO `Option` (`option_image_path`,`option_name`,`option_price`,`option_code`,`option_type_id`) VALUES ('/images/option/HS1.png','현대 스마트센스 Ⅰ',940000,'HS1',1)
INSERT INTO `Option` (`option_code`,`option_price`,`option_name`,`option_type_id`,`option_image_path`) VALUES ('EXD',450000,'익스테리어 디자인',1,'/images/option/EXD.png')
INSERT INTO `Option` (`option_name`,`option_price`,`option_type_id`,`option_image_path`,`option_code`) VALUES ('선루프',450000,1,'/images/option/SRF.png','SRF')
INSERT INTO `Option` (`option_image_path`,`option_code`,`option_price`,`option_name`,`option_type_id`) VALUES ('/images/option/PAP.png','PAP',1290000,'파킹 어시스트 플러스',1)
INSERT INTO `Option` (`option_price`,`option_type_id`,`option_image_path`,`option_name`,`option_code`) VALUES (1140000,1,'/images/option/CM1.png','컴포트 Ⅰ','CM1')
INSERT INTO `Option` (`option_price`,`option_type_id`,`option_image_path`,`option_code`,`option_name`) VALUES (990000,1,'/images/option/CM2.png','CM2','컴포트 Ⅱ')
INSERT INTO `Option` (`option_image_path`,`option_type_id`,`option_code`,`option_name`,`option_price`) VALUES ('/images/option/AT2.png',1,'AT2','17인치 알로이 휠 & 타이어 Ⅱ',300000)
INSERT INTO `Option` (`option_type_id`,`option_code`,`option_price`,`option_image_path`,`option_name`) VALUES (1,'BIC',690000,'/images/option/BIC.png','빌트인 캠(보조배터리 포함)')
INSERT INTO `Option` (`option_image_path`,`option_code`,`option_price`,`option_type_id`,`option_name`) VALUES ('/images/option/SGI.png','SGI',150000,1,'세이지 그린 인테리어 컬러')
INSERT INTO `Option` (`option_price`,`option_code`,`option_image_path`,`option_name`,`option_type_id`) VALUES (1290000,'MN1','/images/option/MN1.png','멀티미디어 내비 Ⅰ',1)
INSERT INTO `Option` (`option_name`,`option_type_id`,`option_image_path`,`option_price`,`option_code`) VALUES ('컨비니언스',1,'/images/option/CON.png',540000,'CON')
INSERT INTO `Option` (`option_name`,`option_code`,`option_price`,`option_image_path`,`option_type_id`) VALUES ('현대 스마트센스','HSS',890000,'/images/option/HSS.png',1)
INSERT INTO `Option` (`option_code`,`option_name`,`option_price`,`option_image_path`,`option_type_id`) VALUES ('EX1','익스테리어 Ⅰ',690000,'/images/option/EX1.png',1)
INSERT INTO `Option` (`option_type_id`,`option_price`,`option_image_path`,`option_code`,`option_name`) VALUES (1,940000,'/images/option/E1P.png','E1P','익스테리어 Ⅰ 플러스')
INSERT INTO `Option` (`option_code`,`option_image_path`,`option_price`,`option_type_id`,`option_name`) VALUES ('PRL','/images/option/PRL.png',1240000,1,'파노라마 선루프 + 루프랙 + LED 실내등(맵램프,룸램프)')
INSERT INTO `Option` (`option_name`,`option_type_id`,`option_code`,`option_price`,`option_image_path`) VALUES ('하이패스+ ECM 룸미러',1,'HEC',250000,'/images/option/HEC.png')
INSERT INTO `Option` (`option_image_path`,`option_name`,`option_price`,`option_type_id`,`option_code`) VALUES ('/images/option/X.png','인테리어디자인 Ⅰ',250000,1,'ID1')
INSERT INTO `Option` (`option_code`,`option_name`,`option_price`,`option_image_path`,`option_type_id`) VALUES ('COM','컴포트',1140000,'/images/option/COM.png',1)
INSERT INTO `Option` (`option_image_path`,`option_type_id`,`option_code`,`option_name`,`option_price`) VALUES ('/images/option/BIC2.png',1,'BIC2','빌트인 캠(보조배터리 포함)',640000)
INSERT INTO `Option` (`option_price`,`option_code`,`option_type_id`,`option_image_path`,`option_name`) VALUES (690000,'EX2',1,'/images/option/EX2.png','익스테리어 Ⅱ')
INSERT INTO `Option` (`option_image_path`,`option_code`,`option_name`,`option_price`,`option_type_id`) VALUES ('/images/option/PSL.png','PSL','파노라마 선루프 + LED 실내등(맵램프,룸램프)',1140000,1)
INSERT INTO `Option` (`option_name`,`option_type_id`,`option_image_path`,`option_code`,`option_price`) VALUES ('인테리어디자인 Ⅱ',1,'/images/option/X.png','ID2',590000)
INSERT INTO `Option` (`option_image_path`,`option_name`,`option_code`,`option_price`,`option_type_id`) VALUES ('/images/option/PL1.png','플래티넘 Ⅰ','PL1',2230000,1)
INSERT INTO `Option` (`option_image_path`,`option_name`,`option_type_id`,`option_code`,`option_price`) VALUES ('/images/option/PL2.png','플래티넘 Ⅱ',1,'PL2',2520000)
INSERT INTO `Option` (`option_image_path`,`option_type_id`,`option_code`,`option_price`,`option_name`) VALUES ('/images/option/PSF.png',1,'PSF',1090000,'파노라마 선루프')
INSERT INTO `Option` (`option_type_id`,`option_name`,`option_image_path`,`option_code`,`option_price`) VALUES (1,'어드벤처패키지','/images/option/X.png','AVP',790000)
INSERT INTO `Option` (`option_code`,`option_name`,`option_image_path`,`option_type_id`,`option_price`) VALUES ('PL3','플래티넘 Ⅲ','/images/option/PL3.png',1,1480000)
INSERT INTO `Option` (`option_code`,`option_image_path`,`option_name`,`option_price`,`option_type_id`) VALUES ('PL4','/images/option/PL4.png','플래티넘 Ⅳ',1780000,1)
INSERT INTO `Option` (`option_image_path`,`option_name`,`option_code`,`option_type_id`,`option_price`) VALUES ('/images/option/NX0002.png','LED 라이팅 패키지 (선루프,
  인스퍼레이션 전용)','NX0002',2,320000)
INSERT INTO `Option` (`option_name`,`option_type_id`,`option_code`,`option_price`,`option_image_path`) VALUES ('러기지 패키지',2,'NX0004',120000,'/images/option/NX0004.png')
INSERT INTO `Option` (`option_name`,`option_code`,`option_price`,`option_type_id`,`option_image_path`) VALUES ('빌트인 공기 청정기','NX0003',400000,2,'/images/option/NX0003.png')
INSERT INTO `Option` (`option_name`,`option_type_id`,`option_code`,`option_price`,`option_image_path`) VALUES ('사이드스텝',2,'NX0008',340000,'/images/option/NX0008.png')
INSERT INTO `Option` (`option_code`,`option_name`,`option_type_id`,`option_price`,`option_image_path`) VALUES ('NX0009','적외선 무릎 워머',2,300000,'/images/option/NX0009.png')
INSERT INTO `Option` (`option_price`,`option_code`,`option_image_path`,`option_type_id`,`option_name`) VALUES (230000,'NX0005','/images/option/NX0005.png',2,'프로텍션 매트 패키지')
INSERT INTO `Option` (`option_type_id`,`option_image_path`,`option_code`,`option_name`,`option_price`) VALUES (2,'/images/option/NX3855.png','NX3855','어드벤처 전용 사이드 스텝',340000)
INSERT INTO `Option` (`option_type_id`,`option_price`,`option_name`,`option_code`,`option_image_path`) VALUES (3,1140000,'19인치 매트 블랙 경량휠','NX3857','/images/option/NX3857.png')
INSERT INTO `Option` (`option_code`,`option_type_id`,`option_price`,`option_name`,`option_image_path`) VALUES ('NX3858',3,2230000,'모노블록 브레이크+19인치 매트 블랙 경량휠 패키지','/images/option/NX3858.png')


INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (1,1)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (2,1)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (3,1)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (1,4)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (5,1)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (4,1)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (2,4)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (4,3)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (4,4)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (4,5)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (2,3)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (6,2)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (7,2)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (8,2)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (9,2)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (10,2)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (12,2)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (2,14)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (5,3)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (6,5)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (5,7)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (5,8)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (5,9)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (11,5)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (5,12)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (14,5)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (3,12)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (8,3)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (13,3)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (14,3)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (6,12)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (6,8)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (6,14)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (22,7)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (7,15)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (7,16)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (7,17)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (18,7)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (19,7)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (20,7)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (7,21)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (34,7)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (35,7)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (7,37)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (38,7)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (7,39)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (41,7)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (7,42)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (10,22)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (10,15)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (16,10)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (17,10)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (18,10)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (10,19)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (20,10)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (21,10)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (34,10)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (35,10)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (10,37)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (10,38)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (39,10)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (41,10)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (10,42)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (22,13)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (15,13)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (13,16)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (17,13)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (13,18)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (13,19)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (20,13)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (13,21)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (34,13)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (35,13)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (13,37)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (13,38)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (13,39)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (13,41)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (42,13)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (22,16)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (15,16)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (16,16)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (17,16)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (16,18)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (16,19)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (20,16)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (21,16)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (16,34)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (16,35)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (16,37)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (38,16)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (39,16)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (16,41)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (16,42)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (8,27)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (8,29)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (8,17)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (8,24)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (8,23)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (8,25)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (26,8)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (8,34)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (8,35)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (8,37)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (38,8)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (39,8)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (36,8)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (41,8)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (8,42)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (11,27)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (11,29)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (17,11)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (11,24)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (23,11)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (25,11)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (26,11)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (11,34)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (35,11)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (37,11)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (38,11)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (11,39)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (11,36)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (11,41)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (42,11)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (27,14)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (28,14)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (14,17)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (14,24)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (14,23)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (25,14)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (26,14)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (14,34)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (14,35)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (37,14)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (38,14)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (39,14)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (36,14)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (41,14)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (42,14)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (27,17)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (28,17)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (17,17)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (17,24)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (17,23)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (25,17)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (17,26)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (34,17)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (35,17)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (37,17)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (38,17)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (39,17)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (17,36)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (17,41)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (17,42)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (9,31)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (30,9)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (24,9)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (9,33)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (34,9)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (35,9)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (37,9)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (9,38)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (39,9)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (36,9)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (9,40)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (9,41)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (42,9)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (31,12)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (30,12)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (12,24)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (12,33)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (12,34)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (12,35)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (37,12)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (12,38)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (39,12)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (12,36)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (12,40)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (41,12)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (12,42)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (15,31)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (30,15)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (24,15)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (15,32)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (34,15)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (35,15)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (15,37)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (38,15)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (39,15)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (15,36)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (40,15)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (41,15)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (42,15)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (31,18)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (30,18)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (18,24)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (32,18)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (34,18)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (35,18)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (37,18)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (38,18)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (39,18)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (18,36)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (18,40)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (41,18)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (42,18)


INSERT INTO `IntColorOption` (`int_color_id`,`option_id`) VALUES (2,14)
INSERT INTO `IntColorOption` (`int_color_id`,`option_id`) VALUES (5,27)
INSERT INTO `IntColorOption` (`option_id`,`int_color_id`) VALUES (27,6)




INSERT INTO `ActivateOption` (`option_id`,`activate_option_id`,`trim_id`) VALUES (1,2,1)
INSERT INTO `ActivateOption` (`activate_option_id`,`trim_id`,`option_id`) VALUES (40,4,31)
INSERT INTO `ActivateOption` (`option_id`,`trim_id`,`activate_option_id`) VALUES (20,2,34)
INSERT INTO `ActivateOption` (`trim_id`,`activate_option_id`,`option_id`) VALUES (3,34,26)
INSERT INTO `ActivateOption` (`trim_id`,`option_id`,`activate_option_id`) VALUES (4,30,34)
INSERT INTO `ActivateOption` (`option_id`,`activate_option_id`,`trim_id`) VALUES (19,41,2)
INSERT INTO `ActivateOption` (`trim_id`,`option_id`,`activate_option_id`) VALUES (2,19,42)
INSERT INTO `ActivateOption` (`trim_id`,`activate_option_id`,`option_id`) VALUES (3,41,25)
INSERT INTO `ActivateOption` (`option_id`,`activate_option_id`,`trim_id`) VALUES (25,42,3)


INSERT INTO `DeactivateOption` (`option_id`,`deactivate_option_id`) VALUES (15,21)
INSERT INTO `DeactivateOption` (`option_id`,`deactivate_option_id`) VALUES (21,15)
INSERT INTO `DeactivateOption` (`deactivate_option_id`,`option_id`) VALUES (19,18)
INSERT INTO `DeactivateOption` (`deactivate_option_id`,`option_id`) VALUES (18,19)
INSERT INTO `DeactivateOption` (`option_id`,`deactivate_option_id`) VALUES (41,42)
INSERT INTO `DeactivateOption` (`option_id`,`deactivate_option_id`) VALUES (42,41)


INSERT INTO `DeleteOption` (`delete_option_id`,`option_id`) VALUES (37,31)
INSERT INTO `DeleteOption` (`option_id`,`delete_option_id`) VALUES (31,41)
INSERT INTO `DeleteOption` (`option_id`,`delete_option_id`) VALUES (31,42)
