INSERT INTO `CarType` (`car_type_code`,`car_type_name`) VALUES ('S','승용')
INSERT INTO `CarType` (`car_type_code`,`car_type_name`) VALUES ('J','SUV')


INSERT INTO `Car` (`car_name`,`car_type_id`,`car_image_path`,`car_code`) VALUES ('더 뉴 아반떼',1,'/images/car/CN12.png','CN12')
INSERT INTO `Car` (`car_image_path`,`car_name`,`car_code`,`car_type_id`) VALUES ('/images/car/NX05.png','투싼','NX05',2)


INSERT INTO `Engine` (`engine_code`,`engine_name`) VALUES ('R','가솔린 1.6')
INSERT INTO `Engine` (`engine_name`,`engine_code`) VALUES ('LPG 1.6','L')
INSERT INTO `Engine` (`engine_name`,`engine_code`) VALUES ('디젤','D')
INSERT INTO `Engine` (`engine_name`,`engine_code`) VALUES ('1.6 가솔린 터보','T')


INSERT INTO `Mission` (`mission_code`,`mission_name`) VALUES ('T','A/T')
INSERT INTO `Mission` (`mission_code`,`mission_name`) VALUES ('A,T','A/T')
INSERT INTO `Mission` (`mission_name`,`mission_code`) VALUES ('DCT','D,H')


INSERT INTO `Drive` (`drive_code`,`drive_name`) VALUES ('D,T','2WD')
INSERT INTO `Drive` (`drive_code`,`drive_name`) VALUES ('A,H','4WD')


INSERT INTO `Trim` (`trim_code`,`trim_name`) VALUES ('B','Smart')
INSERT INTO `Trim` (`trim_code`,`trim_name`) VALUES ('D','Modern')
INSERT INTO `Trim` (`trim_code`,`trim_name`) VALUES ('C','Premium')
INSERT INTO `Trim` (`trim_name`,`trim_code`) VALUES ('Inspiration','P')


INSERT INTO `CarEngine` (`engine_id`,`car_id`) VALUES (1,1)
INSERT INTO `CarEngine` (`car_id`,`engine_id`) VALUES (1,2)
INSERT INTO `CarEngine` (`engine_id`,`car_id`) VALUES (3,2)
INSERT INTO `CarEngine` (`engine_id`,`car_id`) VALUES (4,2)


INSERT INTO `CarMission` (`mission_id`,`car_id`) VALUES (1,1)
INSERT INTO `CarMission` (`mission_id`,`car_id`) VALUES (2,2)
INSERT INTO `CarMission` (`car_id`,`mission_id`) VALUES (2,3)


INSERT INTO `CarDrive` (`drive_id`,`car_id`) VALUES (1,2)
INSERT INTO `CarDrive` (`drive_id`,`car_id`) VALUES (2,2)


INSERT INTO `CarTrim` (`trim_id`,`car_id`) VALUES (1,1)
INSERT INTO `CarTrim` (`trim_id`,`car_id`) VALUES (2,1)
INSERT INTO `CarTrim` (`trim_id`,`car_id`) VALUES (4,1)
INSERT INTO `CarTrim` (`trim_id`,`car_id`) VALUES (2,2)
INSERT INTO `CarTrim` (`car_id`,`trim_id`) VALUES (2,3)
INSERT INTO `CarTrim` (`trim_id`,`car_id`) VALUES (4,2)


INSERT INTO `CarModel` (`drive_id`,`trim_id`,`model_image_path`,`car_id`,`model_name`,`mission_id`,`model_price`,`model_code`,`engine_id`) VALUES (null,1,'/images/model/CN12-smart.png',1,'더 뉴 아반떼 가솔린 1.6 Smart A/T',1,19750000,'CNJS4RBT3',1)
INSERT INTO `CarModel` (`model_price`,`mission_id`,`car_id`,`model_code`,`drive_id`,`model_image_path`,`trim_id`,`engine_id`,`model_name`) VALUES (22730000,1,1,'CNJS4RDT3',null,'/images/model/CN12-modern.png',2,1,'더 뉴 아반떼 가솔린 1.6 Modern A/T')
INSERT INTO `CarModel` (`model_code`,`car_id`,`mission_id`,`model_name`,`drive_id`,`engine_id`,`trim_id`,`model_image_path`,`model_price`) VALUES ('CNJS4RGT3',1,1,'더 뉴 아반떼 가솔린 1.6 Inspiration A/T',null,1,4,'/images/model/CN12-inspiration.png',26910000)
INSERT INTO `CarModel` (`model_price`,`drive_id`,`model_name`,`engine_id`,`model_image_path`,`mission_id`,`car_id`,`trim_id`,`model_code`) VALUES (21150000,null,'더 뉴 아반떼 LPG 1.6 Smart A/T',2,'/images/model/CN12-smart.png',1,1,1,'CNJS4LBT3')
INSERT INTO `CarModel` (`model_code`,`engine_id`,`mission_id`,`model_price`,`model_image_path`,`car_id`,`drive_id`,`trim_id`,`model_name`) VALUES ('CNJS4LDT3',2,1,24120000,'/images/model/CN12-modern.png',1,null,2,'더 뉴 아반떼 LPG 1.6 Modern A/T')
INSERT INTO `CarModel` (`model_image_path`,`car_id`,`model_code`,`drive_id`,`engine_id`,`model_price`,`mission_id`,`trim_id`,`model_name`) VALUES ('/images/model/CN12-inspiration.png',1,'CNJS4LGT3',null,2,28180000,1,4,'더 뉴 아반떼 LPG 1.6 Inspiration A/T')
INSERT INTO `CarModel` (`drive_id`,`mission_id`,`model_code`,`model_price`,`trim_id`,`engine_id`,`model_name`,`model_image_path`,`car_id`) VALUES (1,2,'NXJJ5DDT2',28190000,2,3,'투싼 디젤 Modern 2WD A/T','/images/model/NX05-modern.png',2)
INSERT INTO `CarModel` (`engine_id`,`drive_id`,`model_name`,`car_id`,`model_price`,`trim_id`,`model_code`,`model_image_path`,`mission_id`) VALUES (3,1,'투싼 디젤 Premium 2WD A/T',2,31100000,3,'NXJJ5DCT2','/images/model/NX05-premium.png',2)
INSERT INTO `CarModel` (`model_name`,`trim_id`,`car_id`,`drive_id`,`model_code`,`model_image_path`,`mission_id`,`engine_id`,`model_price`) VALUES ('투싼 디젤 Inspiration 2WD A/T',4,2,1,'NXJJ5DPT2','/images/model/NX05-inspiration.png',2,3,34780000)
INSERT INTO `CarModel` (`car_id`,`model_image_path`,`engine_id`,`model_code`,`model_name`,`drive_id`,`model_price`,`trim_id`,`mission_id`) VALUES (2,'/images/model/NX05-modern.png',3,'NXJJ5DDA2','투싼 디젤 Modern 4WD A/T',2,30420000,2,2)
INSERT INTO `CarModel` (`mission_id`,`model_code`,`model_price`,`car_id`,`drive_id`,`model_image_path`,`trim_id`,`engine_id`,`model_name`) VALUES (2,'NXJJ5DCA2',33330000,2,2,'/images/model/NX05-premium.png',3,3,'투싼 디젤 Premium 4WD A/T')
INSERT INTO `CarModel` (`model_price`,`model_image_path`,`car_id`,`drive_id`,`model_name`,`mission_id`,`model_code`,`trim_id`,`engine_id`) VALUES (37010000,'/images/model/NX05-inspiration.png',2,2,'투싼 디젤 Inspiration 4WD A/T',2,'NXJJ5DPA2',4,3)
INSERT INTO `CarModel` (`model_price`,`model_code`,`model_name`,`mission_id`,`model_image_path`,`engine_id`,`car_id`,`drive_id`,`trim_id`) VALUES (26030000,'NXJJ5TDD2','투싼 1.6 가솔린 터보 Modern 2WD DCT',3,'/images/model/NX05-modern.png',4,2,1,2)
INSERT INTO `CarModel` (`engine_id`,`model_image_path`,`model_price`,`mission_id`,`car_id`,`trim_id`,`model_name`,`drive_id`,`model_code`) VALUES (4,'/images/model/NX05-premium.png',28940000,3,2,3,'투싼 1.6 가솔린 터보 Premium 2WD DCT',1,'NXJJ5TCD2')
INSERT INTO `CarModel` (`trim_id`,`model_image_path`,`model_name`,`model_code`,`car_id`,`mission_id`,`engine_id`,`model_price`,`drive_id`) VALUES (4,'/images/model/NX05-inspiration.png','투싼 1.6 가솔린 터보 Inspiration 2WD DCT','NXJJ5TPD2',2,3,4,32620000,1)
INSERT INTO `CarModel` (`model_image_path`,`engine_id`,`model_name`,`mission_id`,`model_price`,`trim_id`,`car_id`,`model_code`,`drive_id`) VALUES ('/images/model/NX05-modern.png',4,'투싼 1.6 가솔린 터보 Modern 4WD DCT',3,28010000,2,2,'NXJJ5TDH2',2)
INSERT INTO `CarModel` (`car_id`,`mission_id`,`engine_id`,`model_image_path`,`drive_id`,`model_price`,`model_code`,`trim_id`,`model_name`) VALUES (2,3,4,'/images/model/NX05-premium.png',2,30920000,'NXJJ5TCH2',3,'투싼 1.6 가솔린 터보 Premium 4WD DCT')
INSERT INTO `CarModel` (`engine_id`,`model_code`,`model_price`,`model_name`,`trim_id`,`model_image_path`,`car_id`,`mission_id`,`drive_id`) VALUES (4,'NXJJ5TPH2',34600000,'투싼 1.6 가솔린 터보 Inspiration 4WD DCT',4,'/images/model/NX05-inspiration.png',2,3,2)


INSERT INTO `IntColor` (`int_color_image_path`,`int_color_code`,`int_color_name`,`car_id`) VALUES ('/images/interior-color/NNB.png','NNB','블랙모노톤',1)
INSERT INTO `IntColor` (`int_color_name`,`int_color_code`,`int_color_image_path`,`car_id`) VALUES ('세이지그린','SSS','/images/interior-color/SSS.png',1)
INSERT INTO `IntColor` (`int_color_code`,`int_color_name`,`int_color_image_path`,`car_id`) VALUES ('VHC','캐쉬미어 베이지','/images/interior-color/VHC.png',1)
INSERT INTO `IntColor` (`car_id`,`int_color_code`,`int_color_image_path`,`int_color_name`) VALUES (2,'I34','/images/interior-color/I34.png','블랙모노톤')
INSERT INTO `IntColor` (`car_id`,`int_color_name`,`int_color_image_path`,`int_color_code`) VALUES (2,'블랙 모노톤(가죽 시트)','/images/interior-color/I35.png','I35')
INSERT INTO `IntColor` (`car_id`,`int_color_image_path`,`int_color_code`,`int_color_name`) VALUES (2,'/images/interior-color/I36.png','I36','블랙/그레이 투톤(그레이 가죽시트)')
INSERT INTO `IntColor` (`car_id`,`int_color_code`,`int_color_name`,`int_color_image_path`) VALUES (2,'I37','네이비 원톤(인디고 모노톤)','/images/interior-color/I37.png')
INSERT INTO `IntColor` (`int_color_image_path`,`int_color_code`,`car_id`,`int_color_name`) VALUES ('/images/interior-color/I38.png','I38',2,'블랙모노톤(레드스티치)')
INSERT INTO `IntColor` (`int_color_name`,`int_color_code`,`int_color_image_path`,`car_id`) VALUES ('블랙 / 브라운 투톤(브라운 가죽시트)','PRF','/images/interior-color/PRF.png',2)


INSERT INTO `ExtColor` (`car_id`,`ext_color_code`,`ext_color_image_path`,`ext_color_name`) VALUES (1,'A5G','/images/exterior-color/A5G.png','아마존 그레이 메탈릭')
INSERT INTO `ExtColor` (`car_id`,`ext_color_image_path`,`ext_color_code`,`ext_color_name`) VALUES (1,'/images/exterior-color/PE2.png','PE2','에코트로닉 그레이펄')
INSERT INTO `ExtColor` (`ext_color_code`,`car_id`,`ext_color_name`,`ext_color_image_path`) VALUES ('M6T',1,'플루이드 그레이 메탈릭','/images/exterior-color/M6T.png')
INSERT INTO `ExtColor` (`ext_color_image_path`,`ext_color_code`,`ext_color_name`,`car_id`) VALUES ('/images/exterior-color/PM2.png','PM2','메타블루펄',1)
INSERT INTO `ExtColor` (`ext_color_code`,`ext_color_image_path`,`car_id`,`ext_color_name`) VALUES ('YP5','/images/exterior-color/YP5.png',1,'인텐스 블루 펄')
INSERT INTO `ExtColor` (`car_id`,`ext_color_name`,`ext_color_code`,`ext_color_image_path`) VALUES (1,'아틀라스 화이트','SAW','/images/exterior-color/SAW.png')
INSERT INTO `ExtColor` (`ext_color_name`,`car_id`,`ext_color_code`,`ext_color_image_path`) VALUES ('어비스블랙펄',1,'A2B','/images/exterior-color/A2B.png')
INSERT INTO `ExtColor` (`ext_color_code`,`ext_color_image_path`,`car_id`,`ext_color_name`) VALUES ('C5G','/images/exterior-color/C5G.png',1,'사이버 그레이 메탈릭')
INSERT INTO `ExtColor` (`ext_color_image_path`,`car_id`,`ext_color_code`,`ext_color_name`) VALUES ('/images/exterior-color/R2P.png',1,'R2P','얼티메이트 레드 메탈릭')
INSERT INTO `ExtColor` (`ext_color_code`,`car_id`,`ext_color_name`,`ext_color_image_path`) VALUES ('B6S',2,'실키 브론즈 메탈릭','/images/exterior-color/B6S.png')
INSERT INTO `ExtColor` (`ext_color_code`,`ext_color_image_path`,`car_id`,`ext_color_name`) VALUES ('R2T','/images/exterior-color/R2T.png',2,'쉬머링 실버 메탈릭')
INSERT INTO `ExtColor` (`car_id`,`ext_color_code`,`ext_color_image_path`,`ext_color_name`) VALUES (2,'TW3','/images/exterior-color/TW3.png','크리미 화이트 펄')
INSERT INTO `ExtColor` (`ext_color_image_path`,`ext_color_name`,`ext_color_code`,`car_id`) VALUES ('/images/exterior-color/A5G.png','아마존 그레이 메탈릭','A5G',2)
INSERT INTO `ExtColor` (`ext_color_code`,`ext_color_image_path`,`car_id`,`ext_color_name`) VALUES ('R4G','/images/exterior-color/R4G.png',2,'티탄 그레이 메탈릭')
INSERT INTO `ExtColor` (`ext_color_image_path`,`ext_color_name`,`ext_color_code`,`car_id`) VALUES ('/images/exterior-color/PS8.png','오션 인디고 펄','PS8',2)
INSERT INTO `ExtColor` (`car_id`,`ext_color_code`,`ext_color_image_path`,`ext_color_name`) VALUES (2,'TCM','/images/exterior-color/TCM.png','팬텀 블랙 펄')
INSERT INTO `ExtColor` (`car_id`,`ext_color_code`,`ext_color_name`,`ext_color_image_path`) VALUES (2,'Y3G','티타늄 그레이 매트','/images/exterior-color/Y3G.png')


INSERT INTO `IntExtColor` (`int_color_id`,`ext_color_id`) VALUES (1,1)
INSERT INTO `IntExtColor` (`ext_color_id`,`int_color_id`) VALUES (2,1)
INSERT INTO `IntExtColor` (`int_color_id`,`ext_color_id`) VALUES (1,3)
INSERT INTO `IntExtColor` (`ext_color_id`,`int_color_id`) VALUES (4,1)
INSERT INTO `IntExtColor` (`ext_color_id`,`int_color_id`) VALUES (5,1)
INSERT INTO `IntExtColor` (`ext_color_id`,`int_color_id`) VALUES (6,1)
INSERT INTO `IntExtColor` (`ext_color_id`,`int_color_id`) VALUES (7,1)
INSERT INTO `IntExtColor` (`ext_color_id`,`int_color_id`) VALUES (8,1)
INSERT INTO `IntExtColor` (`int_color_id`,`ext_color_id`) VALUES (1,9)
INSERT INTO `IntExtColor` (`ext_color_id`,`int_color_id`) VALUES (1,2)
INSERT INTO `IntExtColor` (`ext_color_id`,`int_color_id`) VALUES (2,2)
INSERT INTO `IntExtColor` (`ext_color_id`,`int_color_id`) VALUES (3,2)
INSERT INTO `IntExtColor` (`ext_color_id`,`int_color_id`) VALUES (6,2)
INSERT INTO `IntExtColor` (`ext_color_id`,`int_color_id`) VALUES (7,2)
INSERT INTO `IntExtColor` (`int_color_id`,`ext_color_id`) VALUES (2,8)
INSERT INTO `IntExtColor` (`ext_color_id`,`int_color_id`) VALUES (1,3)
INSERT INTO `IntExtColor` (`ext_color_id`,`int_color_id`) VALUES (2,3)
INSERT INTO `IntExtColor` (`int_color_id`,`ext_color_id`) VALUES (3,3)
INSERT INTO `IntExtColor` (`int_color_id`,`ext_color_id`) VALUES (3,4)
INSERT INTO `IntExtColor` (`ext_color_id`,`int_color_id`) VALUES (5,3)
INSERT INTO `IntExtColor` (`ext_color_id`,`int_color_id`) VALUES (6,3)
INSERT INTO `IntExtColor` (`int_color_id`,`ext_color_id`) VALUES (3,7)
INSERT INTO `IntExtColor` (`ext_color_id`,`int_color_id`) VALUES (8,3)
INSERT INTO `IntExtColor` (`int_color_id`,`ext_color_id`) VALUES (4,10)
INSERT INTO `IntExtColor` (`int_color_id`,`ext_color_id`) VALUES (4,11)
INSERT INTO `IntExtColor` (`ext_color_id`,`int_color_id`) VALUES (12,4)
INSERT INTO `IntExtColor` (`int_color_id`,`ext_color_id`) VALUES (4,13)
INSERT INTO `IntExtColor` (`ext_color_id`,`int_color_id`) VALUES (14,4)
INSERT INTO `IntExtColor` (`ext_color_id`,`int_color_id`) VALUES (15,4)
INSERT INTO `IntExtColor` (`ext_color_id`,`int_color_id`) VALUES (16,4)
INSERT INTO `IntExtColor` (`int_color_id`,`ext_color_id`) VALUES (5,10)
INSERT INTO `IntExtColor` (`ext_color_id`,`int_color_id`) VALUES (11,5)
INSERT INTO `IntExtColor` (`ext_color_id`,`int_color_id`) VALUES (12,5)
INSERT INTO `IntExtColor` (`ext_color_id`,`int_color_id`) VALUES (13,5)
INSERT INTO `IntExtColor` (`ext_color_id`,`int_color_id`) VALUES (14,5)
INSERT INTO `IntExtColor` (`int_color_id`,`ext_color_id`) VALUES (5,15)
INSERT INTO `IntExtColor` (`int_color_id`,`ext_color_id`) VALUES (5,16)
INSERT INTO `IntExtColor` (`int_color_id`,`ext_color_id`) VALUES (6,10)
INSERT INTO `IntExtColor` (`int_color_id`,`ext_color_id`) VALUES (6,11)
INSERT INTO `IntExtColor` (`int_color_id`,`ext_color_id`) VALUES (6,12)
INSERT INTO `IntExtColor` (`int_color_id`,`ext_color_id`) VALUES (6,13)
INSERT INTO `IntExtColor` (`int_color_id`,`ext_color_id`) VALUES (6,14)
INSERT INTO `IntExtColor` (`int_color_id`,`ext_color_id`) VALUES (6,15)
INSERT INTO `IntExtColor` (`int_color_id`,`ext_color_id`) VALUES (6,16)
INSERT INTO `IntExtColor` (`ext_color_id`,`int_color_id`) VALUES (11,7)
INSERT INTO `IntExtColor` (`int_color_id`,`ext_color_id`) VALUES (7,12)
INSERT INTO `IntExtColor` (`ext_color_id`,`int_color_id`) VALUES (14,7)
INSERT INTO `IntExtColor` (`ext_color_id`,`int_color_id`) VALUES (15,7)
INSERT INTO `IntExtColor` (`int_color_id`,`ext_color_id`) VALUES (7,16)
INSERT INTO `IntExtColor` (`ext_color_id`,`int_color_id`) VALUES (10,9)
INSERT INTO `IntExtColor` (`ext_color_id`,`int_color_id`) VALUES (11,9)
INSERT INTO `IntExtColor` (`ext_color_id`,`int_color_id`) VALUES (12,9)
INSERT INTO `IntExtColor` (`int_color_id`,`ext_color_id`) VALUES (9,13)
INSERT INTO `IntExtColor` (`ext_color_id`,`int_color_id`) VALUES (14,9)
INSERT INTO `IntExtColor` (`int_color_id`,`ext_color_id`) VALUES (9,16)


INSERT INTO `TrimIntColor` (`int_color_id`,`trim_id`) VALUES (1,1)
INSERT INTO `TrimIntColor` (`int_color_id`,`trim_id`) VALUES (1,2)
INSERT INTO `TrimIntColor` (`trim_id`,`int_color_id`) VALUES (2,2)
INSERT INTO `TrimIntColor` (`trim_id`,`int_color_id`) VALUES (4,1)
INSERT INTO `TrimIntColor` (`int_color_id`,`trim_id`) VALUES (2,4)
INSERT INTO `TrimIntColor` (`int_color_id`,`trim_id`) VALUES (3,4)
INSERT INTO `TrimIntColor` (`trim_id`,`int_color_id`) VALUES (2,4)
INSERT INTO `TrimIntColor` (`int_color_id`,`trim_id`) VALUES (4,3)
INSERT INTO `TrimIntColor` (`int_color_id`,`trim_id`) VALUES (5,3)
INSERT INTO `TrimIntColor` (`trim_id`,`int_color_id`) VALUES (3,6)
INSERT INTO `TrimIntColor` (`trim_id`,`int_color_id`) VALUES (4,5)
INSERT INTO `TrimIntColor` (`trim_id`,`int_color_id`) VALUES (4,6)
INSERT INTO `TrimIntColor` (`int_color_id`,`trim_id`) VALUES (7,4)
INSERT INTO `TrimIntColor` (`trim_id`,`int_color_id`) VALUES (4,9)


INSERT INTO `OptionType` (`option_type_name`) VALUES ('detail')
INSERT INTO `OptionType` (`option_type_name`) VALUES ('hga')
INSERT INTO `OptionType` (`option_type_name`) VALUES ('performance')


INSERT INTO `Option` (`option_name`,`option_image_path`,`option_type_id`,`option_code`,`option_price`) VALUES ('컨비니언스 Ⅰ','/images/option/CV1.png',1,'CV1',690000)
INSERT INTO `Option` (`option_price`,`option_name`,`option_image_path`,`option_code`,`option_type_id`) VALUES (790000,'인포테인먼트 내비','/images/option/IFN.png','IFN',1)
INSERT INTO `Option` (`option_name`,`option_type_id`,`option_price`,`option_code`,`option_image_path`) VALUES ('하이패스+ECM 룸미러',1,250000,'HER','/images/option/HER.png')
INSERT INTO `Option` (`option_price`,`option_image_path`,`option_code`,`option_name`,`option_type_id`) VALUES (690000,'/images/option/HS3.png','HS3','현대 스마트센스 Ⅲ',1)
INSERT INTO `Option` (`option_image_path`,`option_price`,`option_type_id`,`option_name`,`option_code`) VALUES ('/images/option/AT1.png',490000,1,'17인치 알로이 휠 & 타이어 Ⅰ','AT1')
INSERT INTO `Option` (`option_type_id`,`option_name`,`option_price`,`option_image_path`,`option_code`) VALUES (1,'현대 스마트센스 Ⅰ',940000,'/images/option/HS1.png','HS1')
INSERT INTO `Option` (`option_code`,`option_name`,`option_type_id`,`option_price`,`option_image_path`) VALUES ('EXD','익스테리어 디자인',1,450000,'/images/option/EXD.png')
INSERT INTO `Option` (`option_type_id`,`option_name`,`option_code`,`option_price`,`option_image_path`) VALUES (1,'선루프','SRF',450000,'/images/option/SRF.png')
INSERT INTO `Option` (`option_type_id`,`option_price`,`option_name`,`option_code`,`option_image_path`) VALUES (1,1290000,'파킹 어시스트 플러스','PAP','/images/option/PAP.png')
INSERT INTO `Option` (`option_code`,`option_price`,`option_name`,`option_type_id`,`option_image_path`) VALUES ('CM1',1140000,'컴포트 Ⅰ',1,'/images/option/CM1.png')
INSERT INTO `Option` (`option_code`,`option_name`,`option_image_path`,`option_price`,`option_type_id`) VALUES ('CM2','컴포트 Ⅱ','/images/option/CM2.png',990000,1)
INSERT INTO `Option` (`option_code`,`option_type_id`,`option_image_path`,`option_price`,`option_name`) VALUES ('AT2',1,'/images/option/AT2.png',300000,'17인치 알로이 휠 & 타이어 Ⅱ')
INSERT INTO `Option` (`option_type_id`,`option_price`,`option_image_path`,`option_code`,`option_name`) VALUES (1,690000,'/images/option/BIC.png','BIC','빌트인 캠(보조배터리 포함)')
INSERT INTO `Option` (`option_name`,`option_type_id`,`option_price`,`option_code`,`option_image_path`) VALUES ('세이지 그린 인테리어 컬러',1,150000,'SGI','/images/option/SGI.png')
INSERT INTO `Option` (`option_code`,`option_price`,`option_image_path`,`option_type_id`,`option_name`) VALUES ('MN1',1290000,'/images/option/MN1.png',1,'멀티미디어 내비 Ⅰ')
INSERT INTO `Option` (`option_type_id`,`option_price`,`option_image_path`,`option_code`,`option_name`) VALUES (1,540000,'/images/option/CON.png','CON','컨비니언스')
INSERT INTO `Option` (`option_name`,`option_image_path`,`option_type_id`,`option_code`,`option_price`) VALUES ('현대 스마트센스','/images/option/HSS.png',1,'HSS',890000)
INSERT INTO `Option` (`option_image_path`,`option_name`,`option_price`,`option_code`,`option_type_id`) VALUES ('/images/option/EX1.png','익스테리어 Ⅰ',690000,'EX1',1)
INSERT INTO `Option` (`option_type_id`,`option_code`,`option_price`,`option_image_path`,`option_name`) VALUES (1,'E1P',940000,'/images/option/E1P.png','익스테리어 Ⅰ 플러스')
INSERT INTO `Option` (`option_image_path`,`option_name`,`option_price`,`option_code`,`option_type_id`) VALUES ('/images/option/PRL.png','파노라마 선루프 + 루프랙 + LED 실내등(맵램프,룸램프)',1240000,'PRL',1)
INSERT INTO `Option` (`option_image_path`,`option_type_id`,`option_price`,`option_name`,`option_code`) VALUES ('/images/option/HEC.png',1,250000,'하이패스+ ECM 룸미러','HEC')
INSERT INTO `Option` (`option_price`,`option_type_id`,`option_name`,`option_code`,`option_image_path`) VALUES (250000,1,'인테리어디자인 Ⅰ','ID1','/images/option/X.png')
INSERT INTO `Option` (`option_price`,`option_code`,`option_image_path`,`option_name`,`option_type_id`) VALUES (1140000,'COM','/images/option/COM.png','컴포트',1)
INSERT INTO `Option` (`option_price`,`option_image_path`,`option_type_id`,`option_name`,`option_code`) VALUES (640000,'/images/option/BIC2.png',1,'빌트인 캠(보조배터리 포함)','BIC2')
INSERT INTO `Option` (`option_name`,`option_price`,`option_image_path`,`option_code`,`option_type_id`) VALUES ('익스테리어 Ⅱ',690000,'/images/option/EX2.png','EX2',1)
INSERT INTO `Option` (`option_image_path`,`option_price`,`option_type_id`,`option_name`,`option_code`) VALUES ('/images/option/PSL.png',1140000,1,'파노라마 선루프 + LED 실내등(맵램프,룸램프)','PSL')
INSERT INTO `Option` (`option_name`,`option_image_path`,`option_code`,`option_price`,`option_type_id`) VALUES ('인테리어디자인 Ⅱ','/images/option/X.png','ID2',590000,1)
INSERT INTO `Option` (`option_type_id`,`option_image_path`,`option_name`,`option_price`,`option_code`) VALUES (1,'/images/option/PL1.png','플래티넘 Ⅰ',2230000,'PL1')
INSERT INTO `Option` (`option_image_path`,`option_code`,`option_price`,`option_name`,`option_type_id`) VALUES ('/images/option/PL2.png','PL2',2520000,'플래티넘 Ⅱ',1)
INSERT INTO `Option` (`option_name`,`option_price`,`option_image_path`,`option_type_id`,`option_code`) VALUES ('파노라마 선루프',1090000,'/images/option/PSF.png',1,'PSF')
INSERT INTO `Option` (`option_name`,`option_image_path`,`option_type_id`,`option_price`,`option_code`) VALUES ('어드벤처패키지','/images/option/X.png',1,790000,'AVP')
INSERT INTO `Option` (`option_name`,`option_image_path`,`option_type_id`,`option_price`,`option_code`) VALUES ('플래티넘 Ⅲ','/images/option/PL3.png',1,1480000,'PL3')
INSERT INTO `Option` (`option_price`,`option_name`,`option_type_id`,`option_code`,`option_image_path`) VALUES (1780000,'플래티넘 Ⅳ',1,'PL4','/images/option/PL4.png')
INSERT INTO `Option` (`option_type_id`,`option_code`,`option_image_path`,`option_price`,`option_name`) VALUES (2,'NX0002','/images/option/NX0002.png',320000,'LED 라이팅 패키지 (선루프,
  인스퍼레이션 전용)')
INSERT INTO `Option` (`option_price`,`option_name`,`option_type_id`,`option_code`,`option_image_path`) VALUES (120000,'러기지 패키지',2,'NX0004','/images/option/NX0004.png')
INSERT INTO `Option` (`option_name`,`option_price`,`option_type_id`,`option_image_path`,`option_code`) VALUES ('빌트인 공기 청정기',400000,2,'/images/option/NX0003.png','NX0003')
INSERT INTO `Option` (`option_name`,`option_type_id`,`option_code`,`option_image_path`,`option_price`) VALUES ('사이드스텝',2,'NX0008','/images/option/NX0008.png',340000)
INSERT INTO `Option` (`option_type_id`,`option_image_path`,`option_code`,`option_price`,`option_name`) VALUES (2,'/images/option/NX0009.png','NX0009',300000,'적외선 무릎 워머')
INSERT INTO `Option` (`option_code`,`option_name`,`option_price`,`option_type_id`,`option_image_path`) VALUES ('NX0005','프로텍션 매트 패키지',230000,2,'/images/option/NX0005.png')
INSERT INTO `Option` (`option_type_id`,`option_code`,`option_image_path`,`option_name`,`option_price`) VALUES (2,'NX3855','/images/option/NX3855.png','어드벤처 전용 사이드 스텝',340000)
INSERT INTO `Option` (`option_price`,`option_image_path`,`option_type_id`,`option_name`,`option_code`) VALUES (1140000,'/images/option/NX3857.png',3,'19인치 매트 블랙 경량휠','NX3857')
INSERT INTO `Option` (`option_price`,`option_type_id`,`option_image_path`,`option_name`,`option_code`) VALUES (2230000,3,'/images/option/NX3858.png','모노블록 브레이크+19인치 매트 블랙 경량휠 패키지','NX3858')


INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (1,1)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (2,1)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (1,3)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (1,4)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (5,1)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (1,4)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (2,4)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (3,4)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (4,4)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (5,4)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (3,2)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (2,6)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (7,2)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (2,8)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (2,9)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (10,2)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (12,2)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (2,14)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (5,3)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (5,6)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (7,5)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (8,5)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (5,9)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (11,5)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (12,5)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (14,5)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (12,3)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (3,8)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (13,3)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (3,14)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (6,12)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (8,6)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (6,14)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (22,7)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (15,7)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (16,7)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (7,17)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (7,18)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (7,19)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (20,7)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (21,7)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (7,35)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (37,7)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (38,7)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (39,7)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (22,10)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (15,10)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (16,10)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (10,17)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (18,10)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (10,19)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (10,20)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (10,21)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (10,35)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (10,37)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (10,38)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (39,10)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (13,22)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (15,13)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (13,16)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (13,17)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (18,13)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (13,19)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (20,13)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (21,13)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (35,13)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (37,13)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (38,13)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (39,13)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (16,22)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (16,15)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (16,16)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (17,16)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (18,16)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (16,19)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (20,16)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (21,16)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (35,16)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (16,37)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (38,16)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (39,16)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (8,27)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (29,8)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (17,8)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (8,24)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (8,23)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (8,25)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (26,8)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (8,35)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (8,37)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (8,38)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (8,39)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (36,8)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (11,27)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (29,11)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (11,17)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (24,11)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (11,23)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (11,25)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (26,11)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (35,11)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (37,11)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (38,11)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (39,11)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (36,11)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (27,14)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (14,28)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (17,14)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (14,24)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (14,23)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (14,25)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (26,14)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (35,14)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (14,37)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (14,38)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (14,39)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (36,14)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (17,27)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (17,28)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (17,17)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (24,17)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (17,23)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (17,25)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (26,17)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (17,35)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (37,17)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (38,17)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (39,17)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (36,17)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (31,9)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (9,30)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (9,24)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (33,9)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (9,35)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (37,9)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (9,38)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (39,9)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (36,9)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (40,9)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (41,9)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (9,42)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (12,31)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (30,12)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (12,24)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (12,33)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (12,35)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (12,37)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (38,12)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (12,39)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (12,36)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (12,40)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (12,41)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (42,12)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (31,15)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (15,30)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (24,15)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (32,15)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (15,35)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (15,37)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (38,15)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (15,39)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (36,15)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (15,40)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (41,15)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (15,42)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (18,31)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (30,18)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (18,24)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (18,32)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (35,18)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (37,18)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (18,38)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (18,39)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (36,18)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (40,18)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (41,18)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (18,42)


INSERT INTO `IntColorOption` (`option_id`,`int_color_id`) VALUES (14,2)
INSERT INTO `IntColorOption` (`option_id`,`int_color_id`) VALUES (27,5)
INSERT INTO `IntColorOption` (`int_color_id`,`option_id`) VALUES (6,27)




INSERT INTO `ActivateOption` (`activate_option_id`,`option_id`,`trim_id`) VALUES (2,1,1)
INSERT INTO `ActivateOption` (`trim_id`,`activate_option_id`,`option_id`) VALUES (4,40,31)
INSERT INTO `ActivateOption` (`trim_id`,`option_id`,`activate_option_id`) VALUES (2,20,34)
INSERT INTO `ActivateOption` (`trim_id`,`option_id`,`activate_option_id`) VALUES (3,26,34)
INSERT INTO `ActivateOption` (`activate_option_id`,`option_id`,`trim_id`) VALUES (34,30,4)
INSERT INTO `ActivateOption` (`trim_id`,`activate_option_id`,`option_id`) VALUES (2,41,19)
INSERT INTO `ActivateOption` (`option_id`,`activate_option_id`,`trim_id`) VALUES (19,42,2)
INSERT INTO `ActivateOption` (`trim_id`,`activate_option_id`,`option_id`) VALUES (3,41,25)
INSERT INTO `ActivateOption` (`trim_id`,`option_id`,`activate_option_id`) VALUES (3,25,42)


INSERT INTO `DeactivateOption` (`option_id`,`deactivate_option_id`) VALUES (15,21)
INSERT INTO `DeactivateOption` (`deactivate_option_id`,`option_id`) VALUES (15,21)
INSERT INTO `DeactivateOption` (`option_id`,`deactivate_option_id`) VALUES (18,19)
INSERT INTO `DeactivateOption` (`deactivate_option_id`,`option_id`) VALUES (19,19)
INSERT INTO `DeactivateOption` (`deactivate_option_id`,`option_id`) VALUES (42,41)
INSERT INTO `DeactivateOption` (`option_id`,`deactivate_option_id`) VALUES (42,41)


INSERT INTO `DeleteOption` (`delete_option_id`,`option_id`) VALUES (37,31)
INSERT INTO `DeleteOption` (`delete_option_id`,`option_id`) VALUES (41,31)
INSERT INTO `DeleteOption` (`delete_option_id`,`option_id`) VALUES (42,31)
