INSERT INTO `CarType` (`car_type_name`,`car_type_code`) VALUES ('승용','S')
INSERT INTO `CarType` (`car_type_name`,`car_type_code`) VALUES ('SUV','J')


INSERT INTO `Car` (`car_code`,`car_type_id`,`car_image_path`,`car_name`) VALUES ('CN12',1,'/images/car/CN12.png','더 뉴 아반떼')
INSERT INTO `Car` (`car_code`,`car_name`,`car_image_path`,`car_type_id`) VALUES ('NX05','투싼','/images/car/NX05.png',2)


INSERT INTO `Engine` (`engine_name`,`engine_code`) VALUES ('가솔린 1.6','R')
INSERT INTO `Engine` (`engine_code`,`engine_name`) VALUES ('L','LPG 1.6')
INSERT INTO `Engine` (`engine_code`,`engine_name`) VALUES ('D','디젤')
INSERT INTO `Engine` (`engine_name`,`engine_code`) VALUES ('1.6 가솔린 터보','T')


INSERT INTO `Mission` (`mission_code`,`mission_name`) VALUES ('T','A/T')
INSERT INTO `Mission` (`mission_name`,`mission_code`) VALUES ('A/T','A,T')
INSERT INTO `Mission` (`mission_code`,`mission_name`) VALUES ('D,H','DCT')


INSERT INTO `Drive` (`drive_name`,`drive_code`) VALUES ('2WD','D,T')
INSERT INTO `Drive` (`drive_name`,`drive_code`) VALUES ('4WD','A,H')


INSERT INTO `Trim` (`trim_code`,`trim_name`) VALUES ('B','Smart')
INSERT INTO `Trim` (`trim_name`,`trim_code`) VALUES ('Modern','D')
INSERT INTO `Trim` (`trim_code`,`trim_name`) VALUES ('C','Premium')
INSERT INTO `Trim` (`trim_name`,`trim_code`) VALUES ('Inspiration','P')


INSERT INTO `CarEngine` (`car_id`,`engine_id`) VALUES (1,1)
INSERT INTO `CarEngine` (`engine_id`,`car_id`) VALUES (2,1)
INSERT INTO `CarEngine` (`car_id`,`engine_id`) VALUES (2,3)
INSERT INTO `CarEngine` (`car_id`,`engine_id`) VALUES (2,4)


INSERT INTO `CarMission` (`car_id`,`mission_id`) VALUES (1,1)
INSERT INTO `CarMission` (`car_id`,`mission_id`) VALUES (2,2)
INSERT INTO `CarMission` (`car_id`,`mission_id`) VALUES (2,3)


INSERT INTO `CarDrive` (`drive_id`,`car_id`) VALUES (1,2)
INSERT INTO `CarDrive` (`car_id`,`drive_id`) VALUES (2,2)


INSERT INTO `CarTrim` (`trim_id`,`car_id`) VALUES (1,1)
INSERT INTO `CarTrim` (`trim_id`,`car_id`) VALUES (2,1)
INSERT INTO `CarTrim` (`trim_id`,`car_id`) VALUES (4,1)
INSERT INTO `CarTrim` (`trim_id`,`car_id`) VALUES (2,2)
INSERT INTO `CarTrim` (`trim_id`,`car_id`) VALUES (3,2)
INSERT INTO `CarTrim` (`trim_id`,`car_id`) VALUES (4,2)


INSERT INTO `CarModel` (`mission_id`,`model_image_path`,`drive_id`,`model_price`,`engine_id`,`model_code`,`trim_id`,`car_id`,`model_name`) VALUES (1,'/images/model/CN12-smart.png',null,19750000,1,'CNJS4RBT3',1,1,'더 뉴 아반떼 가솔린 1.6 Smart A/T')
INSERT INTO `CarModel` (`model_image_path`,`model_price`,`drive_id`,`model_code`,`trim_id`,`car_id`,`model_name`,`mission_id`,`engine_id`) VALUES ('/images/model/CN12-modern.png',22730000,null,'CNJS4RDT3',2,1,'더 뉴 아반떼 가솔린 1.6 Modern A/T',1,1)
INSERT INTO `CarModel` (`model_image_path`,`model_price`,`model_code`,`drive_id`,`trim_id`,`car_id`,`mission_id`,`engine_id`,`model_name`) VALUES ('/images/model/CN12-inspiration.png',26910000,'CNJS4RGT3',null,4,1,1,1,'더 뉴 아반떼 가솔린 1.6 Inspiration A/T')
INSERT INTO `CarModel` (`engine_id`,`drive_id`,`mission_id`,`trim_id`,`car_id`,`model_name`,`model_price`,`model_code`,`model_image_path`) VALUES (2,null,1,1,1,'더 뉴 아반떼 LPG 1.6 Smart A/T',21150000,'CNJS4LBT3','/images/model/CN12-smart.png')
INSERT INTO `CarModel` (`car_id`,`model_code`,`trim_id`,`model_image_path`,`drive_id`,`mission_id`,`engine_id`,`model_price`,`model_name`) VALUES (1,'CNJS4LDT3',2,'/images/model/CN12-modern.png',null,1,2,24120000,'더 뉴 아반떼 LPG 1.6 Modern A/T')
INSERT INTO `CarModel` (`engine_id`,`model_price`,`model_code`,`model_name`,`car_id`,`drive_id`,`mission_id`,`model_image_path`,`trim_id`) VALUES (2,28180000,'CNJS4LGT3','더 뉴 아반떼 LPG 1.6 Inspiration A/T',1,null,1,'/images/model/CN12-inspiration.png',4)
INSERT INTO `CarModel` (`drive_id`,`mission_id`,`car_id`,`engine_id`,`model_code`,`model_name`,`trim_id`,`model_price`,`model_image_path`) VALUES (1,2,2,3,'NXJJ5DDT2','투싼 디젤 Modern 2WD A/T',2,28190000,'/images/model/NX05-modern.png')
INSERT INTO `CarModel` (`model_name`,`engine_id`,`car_id`,`model_price`,`mission_id`,`model_image_path`,`trim_id`,`model_code`,`drive_id`) VALUES ('투싼 디젤 Premium 2WD A/T',3,2,31100000,2,'/images/model/NX05-premium.png',3,'NXJJ5DCT2',1)
INSERT INTO `CarModel` (`trim_id`,`engine_id`,`car_id`,`model_name`,`drive_id`,`mission_id`,`model_code`,`model_price`,`model_image_path`) VALUES (4,3,2,'투싼 디젤 Inspiration 2WD A/T',1,2,'NXJJ5DPT2',34780000,'/images/model/NX05-inspiration.png')
INSERT INTO `CarModel` (`engine_id`,`model_name`,`model_code`,`model_image_path`,`drive_id`,`mission_id`,`car_id`,`model_price`,`trim_id`) VALUES (3,'투싼 디젤 Modern 4WD A/T','NXJJ5DDA2','/images/model/NX05-modern.png',2,2,2,30420000,2)
INSERT INTO `CarModel` (`model_code`,`model_price`,`engine_id`,`drive_id`,`trim_id`,`model_image_path`,`mission_id`,`model_name`,`car_id`) VALUES ('NXJJ5DCA2',33330000,3,2,3,'/images/model/NX05-premium.png',2,'투싼 디젤 Premium 4WD A/T',2)
INSERT INTO `CarModel` (`model_name`,`model_price`,`mission_id`,`engine_id`,`trim_id`,`car_id`,`model_code`,`model_image_path`,`drive_id`) VALUES ('투싼 디젤 Inspiration 4WD A/T',37010000,2,3,4,2,'NXJJ5DPA2','/images/model/NX05-inspiration.png',2)
INSERT INTO `CarModel` (`car_id`,`model_image_path`,`model_price`,`drive_id`,`model_name`,`model_code`,`mission_id`,`trim_id`,`engine_id`) VALUES (2,'/images/model/NX05-modern.png',26030000,1,'투싼 1.6 가솔린 터보 Modern 2WD DCT','NXJJ5TDD2',3,2,4)
INSERT INTO `CarModel` (`model_price`,`model_name`,`trim_id`,`engine_id`,`mission_id`,`car_id`,`model_code`,`model_image_path`,`drive_id`) VALUES (28940000,'투싼 1.6 가솔린 터보 Premium 2WD DCT',3,4,3,2,'NXJJ5TCD2','/images/model/NX05-premium.png',1)
INSERT INTO `CarModel` (`mission_id`,`engine_id`,`model_image_path`,`model_code`,`drive_id`,`model_name`,`trim_id`,`model_price`,`car_id`) VALUES (3,4,'/images/model/NX05-inspiration.png','NXJJ5TPD2',1,'투싼 1.6 가솔린 터보 Inspiration 2WD DCT',4,32620000,2)
INSERT INTO `CarModel` (`engine_id`,`model_code`,`car_id`,`model_price`,`mission_id`,`model_name`,`model_image_path`,`drive_id`,`trim_id`) VALUES (4,'NXJJ5TDH2',2,28010000,3,'투싼 1.6 가솔린 터보 Modern 4WD DCT','/images/model/NX05-modern.png',2,2)
INSERT INTO `CarModel` (`drive_id`,`car_id`,`trim_id`,`model_name`,`mission_id`,`model_price`,`model_image_path`,`engine_id`,`model_code`) VALUES (2,2,3,'투싼 1.6 가솔린 터보 Premium 4WD DCT',3,30920000,'/images/model/NX05-premium.png',4,'NXJJ5TCH2')
INSERT INTO `CarModel` (`drive_id`,`trim_id`,`engine_id`,`model_name`,`model_price`,`mission_id`,`car_id`,`model_image_path`,`model_code`) VALUES (2,4,4,'투싼 1.6 가솔린 터보 Inspiration 4WD DCT',34600000,3,2,'/images/model/NX05-inspiration.png','NXJJ5TPH2')


INSERT INTO `IntColor` (`int_color_image_path`,`int_color_code`,`car_id`,`int_color_name`) VALUES ('/images/interior-color/NNB.png','NNB',1,'블랙모노톤')
INSERT INTO `IntColor` (`car_id`,`int_color_code`,`int_color_image_path`,`int_color_name`) VALUES (1,'SSS','/images/interior-color/SSS.png','세이지그린')
INSERT INTO `IntColor` (`int_color_name`,`car_id`,`int_color_image_path`,`int_color_code`) VALUES ('캐쉬미어 베이지',1,'/images/interior-color/VHC.png','VHC')
INSERT INTO `IntColor` (`int_color_code`,`car_id`,`int_color_image_path`,`int_color_name`) VALUES ('I34',2,'/images/interior-color/I34.png','블랙모노톤')
INSERT INTO `IntColor` (`int_color_image_path`,`car_id`,`int_color_name`,`int_color_code`) VALUES ('/images/interior-color/I35.png',2,'블랙 모노톤(가죽 시트)','I35')
INSERT INTO `IntColor` (`car_id`,`int_color_code`,`int_color_name`,`int_color_image_path`) VALUES (2,'I36','블랙/그레이 투톤(그레이 가죽시트)','/images/interior-color/I36.png')
INSERT INTO `IntColor` (`int_color_code`,`car_id`,`int_color_name`,`int_color_image_path`) VALUES ('I37',2,'네이비 원톤(인디고 모노톤)','/images/interior-color/I37.png')
INSERT INTO `IntColor` (`int_color_code`,`car_id`,`int_color_image_path`,`int_color_name`) VALUES ('I38',2,'/images/interior-color/I38.png','블랙모노톤(레드스티치)')
INSERT INTO `IntColor` (`int_color_image_path`,`int_color_name`,`int_color_code`,`car_id`) VALUES ('/images/interior-color/PRF.png','블랙 / 브라운 투톤(브라운 가죽시트)','PRF',2)


INSERT INTO `ExtColor` (`ext_color_name`,`ext_color_image_path`,`car_id`,`ext_color_code`) VALUES ('아마존 그레이 메탈릭','/images/exterior-color/A5G.png',1,'A5G')
INSERT INTO `ExtColor` (`car_id`,`ext_color_name`,`ext_color_code`,`ext_color_image_path`) VALUES (1,'에코트로닉 그레이펄','PE2','/images/exterior-color/PE2.png')
INSERT INTO `ExtColor` (`ext_color_name`,`ext_color_image_path`,`ext_color_code`,`car_id`) VALUES ('플루이드 그레이 메탈릭','/images/exterior-color/M6T.png','M6T',1)
INSERT INTO `ExtColor` (`ext_color_name`,`car_id`,`ext_color_image_path`,`ext_color_code`) VALUES ('메타블루펄',1,'/images/exterior-color/PM2.png','PM2')
INSERT INTO `ExtColor` (`ext_color_image_path`,`ext_color_code`,`car_id`,`ext_color_name`) VALUES ('/images/exterior-color/YP5.png','YP5',1,'인텐스 블루 펄')
INSERT INTO `ExtColor` (`ext_color_image_path`,`ext_color_name`,`ext_color_code`,`car_id`) VALUES ('/images/exterior-color/SAW.png','아틀라스 화이트','SAW',1)
INSERT INTO `ExtColor` (`ext_color_image_path`,`car_id`,`ext_color_name`,`ext_color_code`) VALUES ('/images/exterior-color/A2B.png',1,'어비스블랙펄','A2B')
INSERT INTO `ExtColor` (`ext_color_code`,`ext_color_name`,`car_id`,`ext_color_image_path`) VALUES ('C5G','사이버 그레이 메탈릭',1,'/images/exterior-color/C5G.png')
INSERT INTO `ExtColor` (`ext_color_name`,`ext_color_image_path`,`car_id`,`ext_color_code`) VALUES ('얼티메이트 레드 메탈릭','/images/exterior-color/R2P.png',1,'R2P')
INSERT INTO `ExtColor` (`ext_color_image_path`,`ext_color_name`,`car_id`,`ext_color_code`) VALUES ('/images/exterior-color/B6S.png','실키 브론즈 메탈릭',2,'B6S')
INSERT INTO `ExtColor` (`ext_color_image_path`,`ext_color_code`,`car_id`,`ext_color_name`) VALUES ('/images/exterior-color/R2T.png','R2T',2,'쉬머링 실버 메탈릭')
INSERT INTO `ExtColor` (`ext_color_name`,`car_id`,`ext_color_code`,`ext_color_image_path`) VALUES ('크리미 화이트 펄',2,'TW3','/images/exterior-color/TW3.png')
INSERT INTO `ExtColor` (`ext_color_name`,`ext_color_image_path`,`ext_color_code`,`car_id`) VALUES ('아마존 그레이 메탈릭','/images/exterior-color/A5G.png','A5G',2)
INSERT INTO `ExtColor` (`ext_color_code`,`ext_color_image_path`,`car_id`,`ext_color_name`) VALUES ('R4G','/images/exterior-color/R4G.png',2,'티탄 그레이 메탈릭')
INSERT INTO `ExtColor` (`ext_color_name`,`ext_color_code`,`car_id`,`ext_color_image_path`) VALUES ('오션 인디고 펄','PS8',2,'/images/exterior-color/PS8.png')
INSERT INTO `ExtColor` (`ext_color_name`,`ext_color_image_path`,`ext_color_code`,`car_id`) VALUES ('팬텀 블랙 펄','/images/exterior-color/TCM.png','TCM',2)
INSERT INTO `ExtColor` (`car_id`,`ext_color_code`,`ext_color_name`,`ext_color_image_path`) VALUES (2,'Y3G','티타늄 그레이 매트','/images/exterior-color/Y3G.png')


INSERT INTO `IntExtColor` (`int_color_id`,`ext_color_id`) VALUES (1,1)
INSERT INTO `IntExtColor` (`int_color_id`,`ext_color_id`) VALUES (1,2)
INSERT INTO `IntExtColor` (`int_color_id`,`ext_color_id`) VALUES (1,3)
INSERT INTO `IntExtColor` (`ext_color_id`,`int_color_id`) VALUES (4,1)
INSERT INTO `IntExtColor` (`ext_color_id`,`int_color_id`) VALUES (5,1)
INSERT INTO `IntExtColor` (`int_color_id`,`ext_color_id`) VALUES (1,6)
INSERT INTO `IntExtColor` (`ext_color_id`,`int_color_id`) VALUES (7,1)
INSERT INTO `IntExtColor` (`int_color_id`,`ext_color_id`) VALUES (1,8)
INSERT INTO `IntExtColor` (`int_color_id`,`ext_color_id`) VALUES (1,9)
INSERT INTO `IntExtColor` (`ext_color_id`,`int_color_id`) VALUES (1,2)
INSERT INTO `IntExtColor` (`ext_color_id`,`int_color_id`) VALUES (2,2)
INSERT INTO `IntExtColor` (`int_color_id`,`ext_color_id`) VALUES (2,3)
INSERT INTO `IntExtColor` (`int_color_id`,`ext_color_id`) VALUES (2,6)
INSERT INTO `IntExtColor` (`int_color_id`,`ext_color_id`) VALUES (2,7)
INSERT INTO `IntExtColor` (`int_color_id`,`ext_color_id`) VALUES (2,8)
INSERT INTO `IntExtColor` (`int_color_id`,`ext_color_id`) VALUES (3,1)
INSERT INTO `IntExtColor` (`ext_color_id`,`int_color_id`) VALUES (2,3)
INSERT INTO `IntExtColor` (`int_color_id`,`ext_color_id`) VALUES (3,3)
INSERT INTO `IntExtColor` (`int_color_id`,`ext_color_id`) VALUES (3,4)
INSERT INTO `IntExtColor` (`int_color_id`,`ext_color_id`) VALUES (3,5)
INSERT INTO `IntExtColor` (`int_color_id`,`ext_color_id`) VALUES (3,6)
INSERT INTO `IntExtColor` (`int_color_id`,`ext_color_id`) VALUES (3,7)
INSERT INTO `IntExtColor` (`ext_color_id`,`int_color_id`) VALUES (8,3)
INSERT INTO `IntExtColor` (`int_color_id`,`ext_color_id`) VALUES (4,10)
INSERT INTO `IntExtColor` (`int_color_id`,`ext_color_id`) VALUES (4,11)
INSERT INTO `IntExtColor` (`ext_color_id`,`int_color_id`) VALUES (12,4)
INSERT INTO `IntExtColor` (`int_color_id`,`ext_color_id`) VALUES (4,13)
INSERT INTO `IntExtColor` (`int_color_id`,`ext_color_id`) VALUES (4,14)
INSERT INTO `IntExtColor` (`ext_color_id`,`int_color_id`) VALUES (15,4)
INSERT INTO `IntExtColor` (`ext_color_id`,`int_color_id`) VALUES (16,4)
INSERT INTO `IntExtColor` (`ext_color_id`,`int_color_id`) VALUES (10,5)
INSERT INTO `IntExtColor` (`ext_color_id`,`int_color_id`) VALUES (11,5)
INSERT INTO `IntExtColor` (`int_color_id`,`ext_color_id`) VALUES (5,12)
INSERT INTO `IntExtColor` (`ext_color_id`,`int_color_id`) VALUES (13,5)
INSERT INTO `IntExtColor` (`int_color_id`,`ext_color_id`) VALUES (5,14)
INSERT INTO `IntExtColor` (`ext_color_id`,`int_color_id`) VALUES (15,5)
INSERT INTO `IntExtColor` (`int_color_id`,`ext_color_id`) VALUES (5,16)
INSERT INTO `IntExtColor` (`int_color_id`,`ext_color_id`) VALUES (6,10)
INSERT INTO `IntExtColor` (`ext_color_id`,`int_color_id`) VALUES (11,6)
INSERT INTO `IntExtColor` (`ext_color_id`,`int_color_id`) VALUES (12,6)
INSERT INTO `IntExtColor` (`int_color_id`,`ext_color_id`) VALUES (6,13)
INSERT INTO `IntExtColor` (`ext_color_id`,`int_color_id`) VALUES (14,6)
INSERT INTO `IntExtColor` (`int_color_id`,`ext_color_id`) VALUES (6,15)
INSERT INTO `IntExtColor` (`ext_color_id`,`int_color_id`) VALUES (16,6)
INSERT INTO `IntExtColor` (`int_color_id`,`ext_color_id`) VALUES (7,11)
INSERT INTO `IntExtColor` (`ext_color_id`,`int_color_id`) VALUES (12,7)
INSERT INTO `IntExtColor` (`int_color_id`,`ext_color_id`) VALUES (7,14)
INSERT INTO `IntExtColor` (`ext_color_id`,`int_color_id`) VALUES (15,7)
INSERT INTO `IntExtColor` (`int_color_id`,`ext_color_id`) VALUES (7,16)
INSERT INTO `IntExtColor` (`int_color_id`,`ext_color_id`) VALUES (9,10)
INSERT INTO `IntExtColor` (`int_color_id`,`ext_color_id`) VALUES (9,11)
INSERT INTO `IntExtColor` (`ext_color_id`,`int_color_id`) VALUES (12,9)
INSERT INTO `IntExtColor` (`int_color_id`,`ext_color_id`) VALUES (9,13)
INSERT INTO `IntExtColor` (`ext_color_id`,`int_color_id`) VALUES (14,9)
INSERT INTO `IntExtColor` (`int_color_id`,`ext_color_id`) VALUES (9,16)


INSERT INTO `TrimIntColor` (`trim_id`,`int_color_id`) VALUES (1,1)
INSERT INTO `TrimIntColor` (`int_color_id`,`trim_id`) VALUES (1,2)
INSERT INTO `TrimIntColor` (`trim_id`,`int_color_id`) VALUES (2,2)
INSERT INTO `TrimIntColor` (`trim_id`,`int_color_id`) VALUES (4,1)
INSERT INTO `TrimIntColor` (`trim_id`,`int_color_id`) VALUES (4,2)
INSERT INTO `TrimIntColor` (`trim_id`,`int_color_id`) VALUES (4,3)
INSERT INTO `TrimIntColor` (`int_color_id`,`trim_id`) VALUES (4,2)
INSERT INTO `TrimIntColor` (`int_color_id`,`trim_id`) VALUES (4,3)
INSERT INTO `TrimIntColor` (`int_color_id`,`trim_id`) VALUES (5,3)
INSERT INTO `TrimIntColor` (`int_color_id`,`trim_id`) VALUES (6,3)
INSERT INTO `TrimIntColor` (`int_color_id`,`trim_id`) VALUES (5,4)
INSERT INTO `TrimIntColor` (`trim_id`,`int_color_id`) VALUES (4,6)
INSERT INTO `TrimIntColor` (`trim_id`,`int_color_id`) VALUES (4,9)


INSERT INTO `Option` (`option_price`,`option_name`,`option_code`) VALUES (700000,'컨비니언스 Ⅰ','CV1')
INSERT INTO `Option` (`option_code`,`option_name`,`option_price`) VALUES ('IFN','인포테인먼트 내비',800000)
INSERT INTO `Option` (`option_price`,`option_code`,`option_name`) VALUES (250000,'HER','하이패스+ECM 룸미러')
INSERT INTO `Option` (`option_price`,`option_name`,`option_code`) VALUES (700000,'현대 스마트센스 Ⅲ','HS3')
INSERT INTO `Option` (`option_name`,`option_price`,`option_code`) VALUES ('17인치 알로이 휠 & 타이어 Ⅰ',500000,'AT1')
INSERT INTO `Option` (`option_code`,`option_name`,`option_price`) VALUES ('SGI','세이지 그린 인테리어 컬러',150000)
INSERT INTO `Option` (`option_price`,`option_code`,`option_name`) VALUES (450000,'SRF','선루프')
INSERT INTO `Option` (`option_name`,`option_price`,`option_code`) VALUES ('파킹 어시스트 플러스',1300000,'PAP')
INSERT INTO `Option` (`option_code`,`option_name`,`option_price`) VALUES ('HS1','현대 스마트센스 Ⅰ',950000)
INSERT INTO `Option` (`option_code`,`option_name`,`option_price`) VALUES ('CM1','컴포트 Ⅰ',1150000)
INSERT INTO `Option` (`option_price`,`option_name`,`option_code`) VALUES (1000000,'컴포트 Ⅱ','CM2')
INSERT INTO `Option` (`option_price`,`option_name`,`option_code`) VALUES (450000,'익스테리어 디자인','EXD')
INSERT INTO `Option` (`option_code`,`option_price`,`option_name`) VALUES ('AT2',300000,'17인치 알로이 휠 & 타이어 Ⅱ')
INSERT INTO `Option` (`option_name`,`option_code`,`option_price`) VALUES ('빌트인 캠(보조배터리 포함)','BIC',700000)
INSERT INTO `Option` (`option_code`,`option_name`,`option_price`) VALUES ('ID1','인테리어디자인 Ⅰ',250000)
INSERT INTO `Option` (`option_name`,`option_price`,`option_code`) VALUES ('멀티미디어 내비 Ⅰ',1300000,'MN1')
INSERT INTO `Option` (`option_price`,`option_code`,`option_name`) VALUES (550000,'CON','컨비니언스')
INSERT INTO `Option` (`option_price`,`option_name`,`option_code`) VALUES (900000,'현대 스마트센스','HSS')
INSERT INTO `Option` (`option_code`,`option_name`,`option_price`) VALUES ('EX1','익스테리어 Ⅰ',700000)
INSERT INTO `Option` (`option_price`,`option_name`,`option_code`) VALUES (950000,'익스테리어 Ⅰ 플러스','E1P')
INSERT INTO `Option` (`option_price`,`option_name`,`option_code`) VALUES (1250000,'파노라마 선루프 + 루프랙 + LED 실내등(맵램프,룸램프)','PRL')
INSERT INTO `Option` (`option_name`,`option_code`,`option_price`) VALUES ('하이패스+ ECM 룸미러','HEC',250000)
INSERT INTO `Option` (`option_price`,`option_code`,`option_name`) VALUES (600000,'ID2','인테리어디자인 Ⅱ')
INSERT INTO `Option` (`option_name`,`option_code`,`option_price`) VALUES ('플래티넘 Ⅰ','PL1',2250000)
INSERT INTO `Option` (`option_name`,`option_price`,`option_code`) VALUES ('플래티넘 Ⅱ',2550000,'PL2')
INSERT INTO `Option` (`option_name`,`option_price`,`option_code`) VALUES ('빌트인 캠(보조배터리 포함)',650000,'BIC2')
INSERT INTO `Option` (`option_code`,`option_price`,`option_name`) VALUES ('COM',1150000,'컴포트')
INSERT INTO `Option` (`option_name`,`option_code`,`option_price`) VALUES ('익스테리어 Ⅱ','EX2',700000)
INSERT INTO `Option` (`option_name`,`option_price`,`option_code`) VALUES ('파노라마 선루프 + LED 실내등(맵램프,룸램프)',1150000,'PSL')
INSERT INTO `Option` (`option_name`,`option_code`,`option_price`) VALUES ('어드벤처패키지','AVP',800000)
INSERT INTO `Option` (`option_name`,`option_code`,`option_price`) VALUES ('파노라마 선루프','PSF',1100000)
INSERT INTO `Option` (`option_name`,`option_price`,`option_code`) VALUES ('플래티넘 Ⅲ',1500000,'PL3')
INSERT INTO `Option` (`option_name`,`option_code`,`option_price`) VALUES ('플래티넘 Ⅳ','PL4',1800000)


INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (1,1)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (1,2)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (1,3)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (1,4)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (5,1)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (4,1)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (4,2)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (4,3)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (4,4)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (5,4)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (2,6)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (2,7)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (3,2)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (2,8)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (9,2)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (10,2)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (2,12)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (13,2)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (6,5)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (7,5)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (3,5)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (5,8)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (5,9)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (10,5)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (12,5)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (13,5)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (3,6)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (3,7)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (13,3)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (6,6)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (7,6)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (6,13)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (7,15)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (16,7)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (17,7)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (7,18)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (7,19)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (7,20)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (7,21)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (22,7)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (10,15)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (16,10)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (17,10)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (10,18)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (19,10)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (10,20)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (21,10)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (22,10)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (15,13)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (13,16)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (17,13)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (13,18)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (19,13)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (20,13)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (21,13)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (13,22)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (16,15)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (16,16)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (16,17)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (18,16)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (16,19)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (16,20)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (16,21)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (22,16)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (8,23)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (25,8)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (8,18)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (8,26)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (27,8)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (8,28)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (8,29)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (23,11)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (25,11)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (11,18)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (11,26)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (27,11)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (11,28)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (29,11)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (23,14)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (14,24)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (18,14)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (14,26)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (14,27)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (14,28)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (14,29)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (23,17)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (24,17)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (17,18)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (26,17)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (27,17)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (17,28)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (17,29)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (30,9)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (31,9)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (9,26)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (9,33)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (12,30)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (31,12)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (12,26)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (12,33)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (15,30)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (31,15)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (26,15)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (32,15)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (18,30)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (31,18)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (26,18)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (32,18)


INSERT INTO `AutoChoiceOption` (`int_color_id`,`option_id`) VALUES (2,6)


INSERT INTO `RequiredOption` (`option_id`,`required_option_id`) VALUES (2,1)


INSERT INTO `DisabledOption` (`option_id`,`disabled_option_id`) VALUES (16,22)
INSERT INTO `DisabledOption` (`option_id`,`disabled_option_id`) VALUES (22,16)


INSERT INTO `Tuix` (`tuix_name`,`tuix_price`,`tuix_code`) VALUES ('LED 라이팅 패키지 (선루프,
  인스퍼레이션 전용)',320000,'NX0002')
INSERT INTO `Tuix` (`tuix_price`,`tuix_name`,`tuix_code`) VALUES (120000,'러기지 패키지','NX0004')
INSERT INTO `Tuix` (`tuix_price`,`tuix_code`,`tuix_name`) VALUES (340000,'NX0008','사이드스텝')
INSERT INTO `Tuix` (`tuix_code`,`tuix_name`,`tuix_price`) VALUES ('NX0009','적외선 무릎 워머',300000)
INSERT INTO `Tuix` (`tuix_name`,`tuix_code`,`tuix_price`) VALUES ('프로텍션 매트 패키지','NX0005',230000)
INSERT INTO `Tuix` (`tuix_price`,`tuix_code`,`tuix_name`) VALUES (1150000,'NX3857','[N퍼포먼스파츠] 19인치 매트 블랙 경량휠')
INSERT INTO `Tuix` (`tuix_code`,`tuix_price`,`tuix_name`) VALUES ('NX3858',2250000,'[N퍼포먼스파츠] 모노블록 브레이크+19인치 매트 블랙 경량휠 패키지')
INSERT INTO `Tuix` (`tuix_name`,`tuix_code`,`tuix_price`) VALUES ('빌트인 공기 청정기','NX0003',400000)
INSERT INTO `Tuix` (`tuix_name`,`tuix_code`,`tuix_price`) VALUES ('어드벤처 전용 사이드 스텝','NX3855',340000)


INSERT INTO `CarModelTuix` (`model_id`,`tuix_id`) VALUES (7,1)
INSERT INTO `CarModelTuix` (`tuix_id`,`model_id`) VALUES (2,7)
INSERT INTO `CarModelTuix` (`model_id`,`tuix_id`) VALUES (7,3)
INSERT INTO `CarModelTuix` (`tuix_id`,`model_id`) VALUES (4,7)
INSERT INTO `CarModelTuix` (`tuix_id`,`model_id`) VALUES (5,7)
INSERT INTO `CarModelTuix` (`tuix_id`,`model_id`) VALUES (6,7)
INSERT INTO `CarModelTuix` (`tuix_id`,`model_id`) VALUES (7,7)
INSERT INTO `CarModelTuix` (`tuix_id`,`model_id`) VALUES (1,10)
INSERT INTO `CarModelTuix` (`model_id`,`tuix_id`) VALUES (10,2)
INSERT INTO `CarModelTuix` (`tuix_id`,`model_id`) VALUES (3,10)
INSERT INTO `CarModelTuix` (`tuix_id`,`model_id`) VALUES (4,10)
INSERT INTO `CarModelTuix` (`model_id`,`tuix_id`) VALUES (10,5)
INSERT INTO `CarModelTuix` (`model_id`,`tuix_id`) VALUES (10,6)
INSERT INTO `CarModelTuix` (`tuix_id`,`model_id`) VALUES (7,10)
INSERT INTO `CarModelTuix` (`tuix_id`,`model_id`) VALUES (1,13)
INSERT INTO `CarModelTuix` (`tuix_id`,`model_id`) VALUES (2,13)
INSERT INTO `CarModelTuix` (`tuix_id`,`model_id`) VALUES (3,13)
INSERT INTO `CarModelTuix` (`model_id`,`tuix_id`) VALUES (13,4)
INSERT INTO `CarModelTuix` (`tuix_id`,`model_id`) VALUES (5,13)
INSERT INTO `CarModelTuix` (`tuix_id`,`model_id`) VALUES (6,13)
INSERT INTO `CarModelTuix` (`tuix_id`,`model_id`) VALUES (7,13)
INSERT INTO `CarModelTuix` (`model_id`,`tuix_id`) VALUES (16,1)
INSERT INTO `CarModelTuix` (`tuix_id`,`model_id`) VALUES (2,16)
INSERT INTO `CarModelTuix` (`tuix_id`,`model_id`) VALUES (3,16)
INSERT INTO `CarModelTuix` (`model_id`,`tuix_id`) VALUES (16,4)
INSERT INTO `CarModelTuix` (`model_id`,`tuix_id`) VALUES (16,5)
INSERT INTO `CarModelTuix` (`model_id`,`tuix_id`) VALUES (16,6)
INSERT INTO `CarModelTuix` (`tuix_id`,`model_id`) VALUES (7,16)
INSERT INTO `CarModelTuix` (`tuix_id`,`model_id`) VALUES (1,8)
INSERT INTO `CarModelTuix` (`model_id`,`tuix_id`) VALUES (8,2)
INSERT INTO `CarModelTuix` (`model_id`,`tuix_id`) VALUES (8,3)
INSERT INTO `CarModelTuix` (`tuix_id`,`model_id`) VALUES (4,8)
INSERT INTO `CarModelTuix` (`tuix_id`,`model_id`) VALUES (5,8)
INSERT INTO `CarModelTuix` (`model_id`,`tuix_id`) VALUES (8,8)
INSERT INTO `CarModelTuix` (`tuix_id`,`model_id`) VALUES (6,8)
INSERT INTO `CarModelTuix` (`tuix_id`,`model_id`) VALUES (7,8)
INSERT INTO `CarModelTuix` (`tuix_id`,`model_id`) VALUES (1,11)
INSERT INTO `CarModelTuix` (`tuix_id`,`model_id`) VALUES (2,11)
INSERT INTO `CarModelTuix` (`tuix_id`,`model_id`) VALUES (3,11)
INSERT INTO `CarModelTuix` (`tuix_id`,`model_id`) VALUES (4,11)
INSERT INTO `CarModelTuix` (`tuix_id`,`model_id`) VALUES (5,11)
INSERT INTO `CarModelTuix` (`model_id`,`tuix_id`) VALUES (11,8)
INSERT INTO `CarModelTuix` (`model_id`,`tuix_id`) VALUES (11,6)
INSERT INTO `CarModelTuix` (`tuix_id`,`model_id`) VALUES (7,11)
INSERT INTO `CarModelTuix` (`tuix_id`,`model_id`) VALUES (1,14)
INSERT INTO `CarModelTuix` (`model_id`,`tuix_id`) VALUES (14,2)
INSERT INTO `CarModelTuix` (`model_id`,`tuix_id`) VALUES (14,3)
INSERT INTO `CarModelTuix` (`model_id`,`tuix_id`) VALUES (14,4)
INSERT INTO `CarModelTuix` (`tuix_id`,`model_id`) VALUES (5,14)
INSERT INTO `CarModelTuix` (`model_id`,`tuix_id`) VALUES (14,8)
INSERT INTO `CarModelTuix` (`model_id`,`tuix_id`) VALUES (14,6)
INSERT INTO `CarModelTuix` (`model_id`,`tuix_id`) VALUES (14,7)
INSERT INTO `CarModelTuix` (`model_id`,`tuix_id`) VALUES (17,1)
INSERT INTO `CarModelTuix` (`tuix_id`,`model_id`) VALUES (2,17)
INSERT INTO `CarModelTuix` (`tuix_id`,`model_id`) VALUES (3,17)
INSERT INTO `CarModelTuix` (`tuix_id`,`model_id`) VALUES (4,17)
INSERT INTO `CarModelTuix` (`tuix_id`,`model_id`) VALUES (5,17)
INSERT INTO `CarModelTuix` (`model_id`,`tuix_id`) VALUES (17,8)
INSERT INTO `CarModelTuix` (`model_id`,`tuix_id`) VALUES (17,6)
INSERT INTO `CarModelTuix` (`model_id`,`tuix_id`) VALUES (17,7)
INSERT INTO `CarModelTuix` (`model_id`,`tuix_id`) VALUES (9,1)
INSERT INTO `CarModelTuix` (`model_id`,`tuix_id`) VALUES (9,2)
INSERT INTO `CarModelTuix` (`tuix_id`,`model_id`) VALUES (3,9)
INSERT INTO `CarModelTuix` (`model_id`,`tuix_id`) VALUES (9,4)
INSERT INTO `CarModelTuix` (`model_id`,`tuix_id`) VALUES (9,5)
INSERT INTO `CarModelTuix` (`model_id`,`tuix_id`) VALUES (9,8)
INSERT INTO `CarModelTuix` (`tuix_id`,`model_id`) VALUES (6,9)
INSERT INTO `CarModelTuix` (`tuix_id`,`model_id`) VALUES (7,9)
INSERT INTO `CarModelTuix` (`tuix_id`,`model_id`) VALUES (9,9)
INSERT INTO `CarModelTuix` (`model_id`,`tuix_id`) VALUES (12,1)
INSERT INTO `CarModelTuix` (`model_id`,`tuix_id`) VALUES (12,2)
INSERT INTO `CarModelTuix` (`tuix_id`,`model_id`) VALUES (3,12)
INSERT INTO `CarModelTuix` (`tuix_id`,`model_id`) VALUES (4,12)
INSERT INTO `CarModelTuix` (`model_id`,`tuix_id`) VALUES (12,5)
INSERT INTO `CarModelTuix` (`tuix_id`,`model_id`) VALUES (8,12)
INSERT INTO `CarModelTuix` (`model_id`,`tuix_id`) VALUES (12,6)
INSERT INTO `CarModelTuix` (`model_id`,`tuix_id`) VALUES (12,7)
INSERT INTO `CarModelTuix` (`tuix_id`,`model_id`) VALUES (9,12)
INSERT INTO `CarModelTuix` (`model_id`,`tuix_id`) VALUES (15,1)
INSERT INTO `CarModelTuix` (`model_id`,`tuix_id`) VALUES (15,2)
INSERT INTO `CarModelTuix` (`tuix_id`,`model_id`) VALUES (3,15)
INSERT INTO `CarModelTuix` (`tuix_id`,`model_id`) VALUES (4,15)
INSERT INTO `CarModelTuix` (`tuix_id`,`model_id`) VALUES (5,15)
INSERT INTO `CarModelTuix` (`tuix_id`,`model_id`) VALUES (8,15)
INSERT INTO `CarModelTuix` (`model_id`,`tuix_id`) VALUES (15,6)
INSERT INTO `CarModelTuix` (`model_id`,`tuix_id`) VALUES (15,7)
INSERT INTO `CarModelTuix` (`tuix_id`,`model_id`) VALUES (9,15)
INSERT INTO `CarModelTuix` (`tuix_id`,`model_id`) VALUES (1,18)
INSERT INTO `CarModelTuix` (`model_id`,`tuix_id`) VALUES (18,2)
INSERT INTO `CarModelTuix` (`tuix_id`,`model_id`) VALUES (3,18)
INSERT INTO `CarModelTuix` (`tuix_id`,`model_id`) VALUES (4,18)
INSERT INTO `CarModelTuix` (`model_id`,`tuix_id`) VALUES (18,5)
INSERT INTO `CarModelTuix` (`model_id`,`tuix_id`) VALUES (18,8)
INSERT INTO `CarModelTuix` (`model_id`,`tuix_id`) VALUES (18,6)
INSERT INTO `CarModelTuix` (`tuix_id`,`model_id`) VALUES (7,18)
INSERT INTO `CarModelTuix` (`tuix_id`,`model_id`) VALUES (9,18)


INSERT INTO `DisabledTuix` (`tuix_id`,`disabled_tuix_id`) VALUES (6,7)
INSERT INTO `DisabledTuix` (`tuix_id`,`disabled_tuix_id`) VALUES (7,6)


INSERT INTO `TuixRequiredOption` (`tuix_id`,`option_id`) VALUES (1,21)
INSERT INTO `TuixRequiredOption` (`tuix_id`,`option_id`) VALUES (1,29)
INSERT INTO `TuixRequiredOption` (`tuix_id`,`option_id`) VALUES (1,31)
INSERT INTO `TuixRequiredOption` (`tuix_id`,`option_id`) VALUES (6,20)
INSERT INTO `TuixRequiredOption` (`tuix_id`,`option_id`) VALUES (7,20)
INSERT INTO `TuixRequiredOption` (`option_id`,`tuix_id`) VALUES (28,6)
INSERT INTO `TuixRequiredOption` (`option_id`,`tuix_id`) VALUES (28,7)
