INSERT INTO `CarType` (`car_type_code`,`car_type_name`) VALUES ('S','승용')
INSERT INTO `CarType` (`car_type_code`,`car_type_name`) VALUES ('J','SUV')


INSERT INTO `Car` (`car_image_path`,`car_type_id`,`car_code`,`car_name`) VALUES ('/images/car/CN12.png',1,'CN12','더 뉴 아반떼')
INSERT INTO `Car` (`car_code`,`car_image_path`,`car_name`,`car_type_id`) VALUES ('NX05','/images/car/NX05.png','투싼',2)


INSERT INTO `Engine` (`engine_code`,`engine_name`) VALUES ('R','가솔린 1.6')
INSERT INTO `Engine` (`engine_name`,`engine_code`) VALUES ('LPG 1.6','L')
INSERT INTO `Engine` (`engine_code`,`engine_name`) VALUES ('D','디젤')
INSERT INTO `Engine` (`engine_name`,`engine_code`) VALUES ('1.6 가솔린 터보','T')


INSERT INTO `Mission` (`mission_name`,`mission_code`) VALUES ('A/T','T')
INSERT INTO `Mission` (`mission_name`,`mission_code`) VALUES ('A/T','A,T')
INSERT INTO `Mission` (`mission_name`,`mission_code`) VALUES ('DCT','D,H')


INSERT INTO `Drive` (`drive_name`,`drive_code`) VALUES ('2WD','D,T')
INSERT INTO `Drive` (`drive_name`,`drive_code`) VALUES ('4WD','A,H')


INSERT INTO `Trim` (`trim_name`,`trim_code`) VALUES ('Smart','B')
INSERT INTO `Trim` (`trim_name`,`trim_code`) VALUES ('Modern','D')
INSERT INTO `Trim` (`trim_code`,`trim_name`) VALUES ('C','Premium')
INSERT INTO `Trim` (`trim_code`,`trim_name`) VALUES ('P','Inspiration')


INSERT INTO `CarEngine` (`engine_id`,`car_id`) VALUES (1,1)
INSERT INTO `CarEngine` (`car_id`,`engine_id`) VALUES (1,2)
INSERT INTO `CarEngine` (`engine_id`,`car_id`) VALUES (3,2)
INSERT INTO `CarEngine` (`car_id`,`engine_id`) VALUES (2,4)


INSERT INTO `CarMission` (`car_id`,`mission_id`) VALUES (1,1)
INSERT INTO `CarMission` (`mission_id`,`car_id`) VALUES (2,2)
INSERT INTO `CarMission` (`mission_id`,`car_id`) VALUES (3,2)


INSERT INTO `CarDrive` (`drive_id`,`car_id`) VALUES (1,2)
INSERT INTO `CarDrive` (`car_id`,`drive_id`) VALUES (2,2)


INSERT INTO `CarTrim` (`car_id`,`trim_id`) VALUES (1,1)
INSERT INTO `CarTrim` (`trim_id`,`car_id`) VALUES (2,1)
INSERT INTO `CarTrim` (`car_id`,`trim_id`) VALUES (1,4)
INSERT INTO `CarTrim` (`trim_id`,`car_id`) VALUES (2,2)
INSERT INTO `CarTrim` (`trim_id`,`car_id`) VALUES (3,2)
INSERT INTO `CarTrim` (`car_id`,`trim_id`) VALUES (2,4)


INSERT INTO `CarModel` (`trim_id`,`model_image_path`,`car_id`,`model_code`,`model_price`,`drive_id`,`engine_id`,`mission_id`,`model_name`) VALUES (1,'/images/model/CN12-smart.png',1,'CNJS4RBT3',19750000,null,1,1,'더 뉴 아반떼 가솔린 1.6 Smart A/T')
INSERT INTO `CarModel` (`model_code`,`mission_id`,`car_id`,`model_price`,`drive_id`,`model_image_path`,`trim_id`,`model_name`,`engine_id`) VALUES ('CNJS4RDT3',1,1,22730000,null,'/images/model/CN12-modern.png',2,'더 뉴 아반떼 가솔린 1.6 Modern A/T',1)
INSERT INTO `CarModel` (`mission_id`,`engine_id`,`drive_id`,`car_id`,`trim_id`,`model_name`,`model_image_path`,`model_price`,`model_code`) VALUES (1,1,null,1,4,'더 뉴 아반떼 가솔린 1.6 Inspiration A/T','/images/model/CN12-inspiration.png',26910000,'CNJS4RGT3')
INSERT INTO `CarModel` (`model_name`,`car_id`,`trim_id`,`mission_id`,`model_image_path`,`drive_id`,`engine_id`,`model_code`,`model_price`) VALUES ('더 뉴 아반떼 LPG 1.6 Smart A/T',1,1,1,'/images/model/CN12-smart.png',null,2,'CNJS4LBT3',21150000)
INSERT INTO `CarModel` (`model_price`,`model_name`,`drive_id`,`model_code`,`trim_id`,`mission_id`,`model_image_path`,`engine_id`,`car_id`) VALUES (24120000,'더 뉴 아반떼 LPG 1.6 Modern A/T',null,'CNJS4LDT3',2,1,'/images/model/CN12-modern.png',2,1)
INSERT INTO `CarModel` (`drive_id`,`trim_id`,`mission_id`,`model_price`,`car_id`,`engine_id`,`model_image_path`,`model_name`,`model_code`) VALUES (null,4,1,28180000,1,2,'/images/model/CN12-inspiration.png','더 뉴 아반떼 LPG 1.6 Inspiration A/T','CNJS4LGT3')
INSERT INTO `CarModel` (`model_name`,`trim_id`,`engine_id`,`model_price`,`mission_id`,`drive_id`,`model_code`,`model_image_path`,`car_id`) VALUES ('투싼 디젤 Modern 2WD A/T',2,3,28190000,2,1,'NXJJ5DDT2','/images/model/NX05-modern.png',2)
INSERT INTO `CarModel` (`car_id`,`model_code`,`model_image_path`,`mission_id`,`model_price`,`drive_id`,`trim_id`,`model_name`,`engine_id`) VALUES (2,'NXJJ5DCT2','/images/model/NX05-premium.png',2,31100000,1,3,'투싼 디젤 Premium 2WD A/T',3)
INSERT INTO `CarModel` (`model_price`,`engine_id`,`trim_id`,`mission_id`,`model_name`,`car_id`,`model_code`,`model_image_path`,`drive_id`) VALUES (34780000,3,4,2,'투싼 디젤 Inspiration 2WD A/T',2,'NXJJ5DPT2','/images/model/NX05-inspiration.png',1)
INSERT INTO `CarModel` (`model_price`,`trim_id`,`engine_id`,`model_name`,`drive_id`,`model_image_path`,`car_id`,`mission_id`,`model_code`) VALUES (30420000,2,3,'투싼 디젤 Modern 4WD A/T',2,'/images/model/NX05-modern.png',2,2,'NXJJ5DDA2')
INSERT INTO `CarModel` (`drive_id`,`model_name`,`engine_id`,`model_price`,`model_image_path`,`car_id`,`model_code`,`mission_id`,`trim_id`) VALUES (2,'투싼 디젤 Premium 4WD A/T',3,33330000,'/images/model/NX05-premium.png',2,'NXJJ5DCA2',2,3)
INSERT INTO `CarModel` (`model_code`,`mission_id`,`model_name`,`trim_id`,`model_price`,`drive_id`,`model_image_path`,`car_id`,`engine_id`) VALUES ('NXJJ5DPA2',2,'투싼 디젤 Inspiration 4WD A/T',4,37010000,2,'/images/model/NX05-inspiration.png',2,3)
INSERT INTO `CarModel` (`model_image_path`,`engine_id`,`mission_id`,`model_code`,`model_price`,`model_name`,`car_id`,`trim_id`,`drive_id`) VALUES ('/images/model/NX05-modern.png',4,3,'NXJJ5TDD2',26030000,'투싼 1.6 가솔린 터보 Modern 2WD DCT',2,2,1)
INSERT INTO `CarModel` (`mission_id`,`engine_id`,`model_price`,`drive_id`,`trim_id`,`model_code`,`car_id`,`model_image_path`,`model_name`) VALUES (3,4,28940000,1,3,'NXJJ5TCD2',2,'/images/model/NX05-premium.png','투싼 1.6 가솔린 터보 Premium 2WD DCT')
INSERT INTO `CarModel` (`model_price`,`car_id`,`drive_id`,`engine_id`,`trim_id`,`model_name`,`mission_id`,`model_code`,`model_image_path`) VALUES (32620000,2,1,4,4,'투싼 1.6 가솔린 터보 Inspiration 2WD DCT',3,'NXJJ5TPD2','/images/model/NX05-inspiration.png')
INSERT INTO `CarModel` (`car_id`,`model_code`,`mission_id`,`drive_id`,`model_name`,`model_price`,`engine_id`,`trim_id`,`model_image_path`) VALUES (2,'NXJJ5TDH2',3,2,'투싼 1.6 가솔린 터보 Modern 4WD DCT',28010000,4,2,'/images/model/NX05-modern.png')
INSERT INTO `CarModel` (`trim_id`,`model_image_path`,`drive_id`,`model_name`,`mission_id`,`engine_id`,`car_id`,`model_code`,`model_price`) VALUES (3,'/images/model/NX05-premium.png',2,'투싼 1.6 가솔린 터보 Premium 4WD DCT',3,4,2,'NXJJ5TCH2',30920000)
INSERT INTO `CarModel` (`model_image_path`,`model_name`,`trim_id`,`mission_id`,`engine_id`,`drive_id`,`car_id`,`model_price`,`model_code`) VALUES ('/images/model/NX05-inspiration.png','투싼 1.6 가솔린 터보 Inspiration 4WD DCT',4,3,4,2,2,34600000,'NXJJ5TPH2')


INSERT INTO `IntColor` (`int_color_image_path`,`car_id`,`int_color_name`,`int_color_code`) VALUES ('/images/interior-color/NNB.png',1,'블랙모노톤','NNB')
INSERT INTO `IntColor` (`int_color_name`,`int_color_code`,`int_color_image_path`,`car_id`) VALUES ('세이지그린','SSS','/images/interior-color/SSS.png',1)
INSERT INTO `IntColor` (`int_color_image_path`,`int_color_name`,`int_color_code`,`car_id`) VALUES ('/images/interior-color/VHC.png','캐쉬미어 베이지','VHC',1)
INSERT INTO `IntColor` (`car_id`,`int_color_name`,`int_color_code`,`int_color_image_path`) VALUES (2,'블랙모노톤','I34','/images/interior-color/I34.png')
INSERT INTO `IntColor` (`int_color_code`,`car_id`,`int_color_name`,`int_color_image_path`) VALUES ('I35',2,'블랙 모노톤(가죽 시트)','/images/interior-color/I35.png')
INSERT INTO `IntColor` (`int_color_name`,`car_id`,`int_color_image_path`,`int_color_code`) VALUES ('블랙/그레이 투톤(그레이 가죽시트)',2,'/images/interior-color/I36.png','I36')
INSERT INTO `IntColor` (`int_color_image_path`,`int_color_code`,`car_id`,`int_color_name`) VALUES ('/images/interior-color/I37.png','I37',2,'네이비 원톤(인디고 모노톤)')
INSERT INTO `IntColor` (`int_color_name`,`int_color_image_path`,`int_color_code`,`car_id`) VALUES ('블랙모노톤(레드스티치)','/images/interior-color/I38.png','I38',2)
INSERT INTO `IntColor` (`int_color_code`,`int_color_name`,`int_color_image_path`,`car_id`) VALUES ('PRF','블랙 / 브라운 투톤(브라운 가죽시트)','/images/interior-color/PRF.png',2)


INSERT INTO `ExtColor` (`car_id`,`ext_color_image_path`,`ext_color_name`,`ext_color_code`) VALUES (1,'/images/exterior-color/A5G.png','아마존 그레이 메탈릭','A5G')
INSERT INTO `ExtColor` (`ext_color_image_path`,`ext_color_name`,`ext_color_code`,`car_id`) VALUES ('/images/exterior-color/PE2.png','에코트로닉 그레이펄','PE2',1)
INSERT INTO `ExtColor` (`ext_color_code`,`ext_color_name`,`car_id`,`ext_color_image_path`) VALUES ('M6T','플루이드 그레이 메탈릭',1,'/images/exterior-color/M6T.png')
INSERT INTO `ExtColor` (`ext_color_name`,`car_id`,`ext_color_code`,`ext_color_image_path`) VALUES ('메타블루펄',1,'PM2','/images/exterior-color/PM2.png')
INSERT INTO `ExtColor` (`car_id`,`ext_color_image_path`,`ext_color_name`,`ext_color_code`) VALUES (1,'/images/exterior-color/YP5.png','인텐스 블루 펄','YP5')
INSERT INTO `ExtColor` (`ext_color_name`,`ext_color_image_path`,`car_id`,`ext_color_code`) VALUES ('아틀라스 화이트','/images/exterior-color/SAW.png',1,'SAW')
INSERT INTO `ExtColor` (`ext_color_image_path`,`car_id`,`ext_color_name`,`ext_color_code`) VALUES ('/images/exterior-color/R2P.png',1,'얼티메이트 레드 메탈릭','R2P')
INSERT INTO `ExtColor` (`ext_color_code`,`ext_color_name`,`car_id`,`ext_color_image_path`) VALUES ('A2B','어비스블랙펄',1,'/images/exterior-color/A2B.png')
INSERT INTO `ExtColor` (`ext_color_name`,`ext_color_image_path`,`ext_color_code`,`car_id`) VALUES ('사이버 그레이 메탈릭','/images/exterior-color/C5G.png','C5G',1)
INSERT INTO `ExtColor` (`ext_color_code`,`ext_color_image_path`,`car_id`,`ext_color_name`) VALUES ('B6S','/images/exterior-color/B6S.png',2,'실키 브론즈 메탈릭')
INSERT INTO `ExtColor` (`ext_color_code`,`ext_color_name`,`ext_color_image_path`,`car_id`) VALUES ('R2T','쉬머링 실버 메탈릭','/images/exterior-color/R2T.png',2)
INSERT INTO `ExtColor` (`ext_color_name`,`ext_color_code`,`car_id`,`ext_color_image_path`) VALUES ('크리미 화이트 펄','TW3',2,'/images/exterior-color/TW3.png')
INSERT INTO `ExtColor` (`ext_color_image_path`,`car_id`,`ext_color_code`,`ext_color_name`) VALUES ('/images/exterior-color/A5G.png',2,'A5G','아마존 그레이 메탈릭')
INSERT INTO `ExtColor` (`car_id`,`ext_color_name`,`ext_color_image_path`,`ext_color_code`) VALUES (2,'티탄 그레이 메탈릭','/images/exterior-color/R4G.png','R4G')
INSERT INTO `ExtColor` (`ext_color_code`,`car_id`,`ext_color_name`,`ext_color_image_path`) VALUES ('PS8',2,'오션 인디고 펄','/images/exterior-color/PS8.png')
INSERT INTO `ExtColor` (`ext_color_image_path`,`car_id`,`ext_color_code`,`ext_color_name`) VALUES ('/images/exterior-color/TCM.png',2,'TCM','팬텀 블랙 펄')
INSERT INTO `ExtColor` (`ext_color_image_path`,`ext_color_name`,`car_id`,`ext_color_code`) VALUES ('/images/exterior-color/Y3G.png','티타늄 그레이 매트',2,'Y3G')


INSERT INTO `IntExtColor` (`ext_color_id`,`int_color_id`) VALUES (1,1)
INSERT INTO `IntExtColor` (`ext_color_id`,`int_color_id`) VALUES (2,1)
INSERT INTO `IntExtColor` (`ext_color_id`,`int_color_id`) VALUES (3,1)
INSERT INTO `IntExtColor` (`ext_color_id`,`int_color_id`) VALUES (4,1)
INSERT INTO `IntExtColor` (`int_color_id`,`ext_color_id`) VALUES (1,5)
INSERT INTO `IntExtColor` (`ext_color_id`,`int_color_id`) VALUES (6,1)
INSERT INTO `IntExtColor` (`int_color_id`,`ext_color_id`) VALUES (1,8)
INSERT INTO `IntExtColor` (`int_color_id`,`ext_color_id`) VALUES (1,9)
INSERT INTO `IntExtColor` (`ext_color_id`,`int_color_id`) VALUES (7,1)
INSERT INTO `IntExtColor` (`ext_color_id`,`int_color_id`) VALUES (1,2)
INSERT INTO `IntExtColor` (`int_color_id`,`ext_color_id`) VALUES (2,2)
INSERT INTO `IntExtColor` (`int_color_id`,`ext_color_id`) VALUES (2,3)
INSERT INTO `IntExtColor` (`ext_color_id`,`int_color_id`) VALUES (6,2)
INSERT INTO `IntExtColor` (`int_color_id`,`ext_color_id`) VALUES (2,8)
INSERT INTO `IntExtColor` (`int_color_id`,`ext_color_id`) VALUES (2,9)
INSERT INTO `IntExtColor` (`int_color_id`,`ext_color_id`) VALUES (3,1)
INSERT INTO `IntExtColor` (`ext_color_id`,`int_color_id`) VALUES (2,3)
INSERT INTO `IntExtColor` (`int_color_id`,`ext_color_id`) VALUES (3,3)
INSERT INTO `IntExtColor` (`int_color_id`,`ext_color_id`) VALUES (3,4)
INSERT INTO `IntExtColor` (`ext_color_id`,`int_color_id`) VALUES (5,3)
INSERT INTO `IntExtColor` (`ext_color_id`,`int_color_id`) VALUES (6,3)
INSERT INTO `IntExtColor` (`ext_color_id`,`int_color_id`) VALUES (8,3)
INSERT INTO `IntExtColor` (`int_color_id`,`ext_color_id`) VALUES (3,9)
INSERT INTO `IntExtColor` (`int_color_id`,`ext_color_id`) VALUES (4,10)
INSERT INTO `IntExtColor` (`ext_color_id`,`int_color_id`) VALUES (11,4)
INSERT INTO `IntExtColor` (`ext_color_id`,`int_color_id`) VALUES (12,4)
INSERT INTO `IntExtColor` (`ext_color_id`,`int_color_id`) VALUES (13,4)
INSERT INTO `IntExtColor` (`ext_color_id`,`int_color_id`) VALUES (14,4)
INSERT INTO `IntExtColor` (`ext_color_id`,`int_color_id`) VALUES (15,4)
INSERT INTO `IntExtColor` (`ext_color_id`,`int_color_id`) VALUES (16,4)
INSERT INTO `IntExtColor` (`int_color_id`,`ext_color_id`) VALUES (5,10)
INSERT INTO `IntExtColor` (`ext_color_id`,`int_color_id`) VALUES (11,5)
INSERT INTO `IntExtColor` (`ext_color_id`,`int_color_id`) VALUES (12,5)
INSERT INTO `IntExtColor` (`int_color_id`,`ext_color_id`) VALUES (5,13)
INSERT INTO `IntExtColor` (`int_color_id`,`ext_color_id`) VALUES (5,14)
INSERT INTO `IntExtColor` (`ext_color_id`,`int_color_id`) VALUES (15,5)
INSERT INTO `IntExtColor` (`ext_color_id`,`int_color_id`) VALUES (16,5)
INSERT INTO `IntExtColor` (`int_color_id`,`ext_color_id`) VALUES (6,10)
INSERT INTO `IntExtColor` (`int_color_id`,`ext_color_id`) VALUES (6,11)
INSERT INTO `IntExtColor` (`int_color_id`,`ext_color_id`) VALUES (6,12)
INSERT INTO `IntExtColor` (`int_color_id`,`ext_color_id`) VALUES (6,13)
INSERT INTO `IntExtColor` (`ext_color_id`,`int_color_id`) VALUES (14,6)
INSERT INTO `IntExtColor` (`ext_color_id`,`int_color_id`) VALUES (15,6)
INSERT INTO `IntExtColor` (`int_color_id`,`ext_color_id`) VALUES (6,16)
INSERT INTO `IntExtColor` (`ext_color_id`,`int_color_id`) VALUES (11,7)
INSERT INTO `IntExtColor` (`ext_color_id`,`int_color_id`) VALUES (12,7)
INSERT INTO `IntExtColor` (`ext_color_id`,`int_color_id`) VALUES (14,7)
INSERT INTO `IntExtColor` (`int_color_id`,`ext_color_id`) VALUES (7,15)
INSERT INTO `IntExtColor` (`int_color_id`,`ext_color_id`) VALUES (7,16)
INSERT INTO `IntExtColor` (`ext_color_id`,`int_color_id`) VALUES (10,9)
INSERT INTO `IntExtColor` (`int_color_id`,`ext_color_id`) VALUES (9,11)
INSERT INTO `IntExtColor` (`ext_color_id`,`int_color_id`) VALUES (12,9)
INSERT INTO `IntExtColor` (`int_color_id`,`ext_color_id`) VALUES (9,13)
INSERT INTO `IntExtColor` (`int_color_id`,`ext_color_id`) VALUES (9,14)
INSERT INTO `IntExtColor` (`ext_color_id`,`int_color_id`) VALUES (16,9)


INSERT INTO `TrimIntColor` (`trim_id`,`int_color_id`) VALUES (1,1)
INSERT INTO `TrimIntColor` (`int_color_id`,`trim_id`) VALUES (1,2)
INSERT INTO `TrimIntColor` (`trim_id`,`int_color_id`) VALUES (2,2)
INSERT INTO `TrimIntColor` (`int_color_id`,`trim_id`) VALUES (1,4)
INSERT INTO `TrimIntColor` (`int_color_id`,`trim_id`) VALUES (2,4)
INSERT INTO `TrimIntColor` (`trim_id`,`int_color_id`) VALUES (4,3)
INSERT INTO `TrimIntColor` (`trim_id`,`int_color_id`) VALUES (2,4)
INSERT INTO `TrimIntColor` (`trim_id`,`int_color_id`) VALUES (3,4)
INSERT INTO `TrimIntColor` (`int_color_id`,`trim_id`) VALUES (5,3)
INSERT INTO `TrimIntColor` (`trim_id`,`int_color_id`) VALUES (3,6)
INSERT INTO `TrimIntColor` (`int_color_id`,`trim_id`) VALUES (5,4)
INSERT INTO `TrimIntColor` (`trim_id`,`int_color_id`) VALUES (4,6)
INSERT INTO `TrimIntColor` (`trim_id`,`int_color_id`) VALUES (4,7)
INSERT INTO `TrimIntColor` (`trim_id`,`int_color_id`) VALUES (4,9)


INSERT INTO `OptionType` (`option_type_name`) VALUES ('detail')
INSERT INTO `OptionType` (`option_type_name`) VALUES ('hga')
INSERT INTO `OptionType` (`option_type_name`) VALUES ('performance')


INSERT INTO `Option` (`option_name`,`option_type_id`,`option_price`,`option_code`,`option_image_path`) VALUES ('컨비니언스 Ⅰ',1,690000,'CV1','/images/option/CV1.png')
INSERT INTO `Option` (`option_name`,`option_price`,`option_type_id`,`option_image_path`,`option_code`) VALUES ('인포테인먼트 내비',790000,1,'/images/option/IFN.png','IFN')
INSERT INTO `Option` (`option_price`,`option_image_path`,`option_name`,`option_code`,`option_type_id`) VALUES (250000,'/images/option/HER.png','하이패스+ECM 룸미러','HER',1)
INSERT INTO `Option` (`option_image_path`,`option_type_id`,`option_code`,`option_name`,`option_price`) VALUES ('/images/option/HS3.png',1,'HS3','현대 스마트센스 Ⅲ',690000)
INSERT INTO `Option` (`option_type_id`,`option_price`,`option_name`,`option_code`,`option_image_path`) VALUES (1,490000,'17인치 알로이 휠 & 타이어 Ⅰ','AT1','/images/option/AT1.png')
INSERT INTO `Option` (`option_code`,`option_image_path`,`option_type_id`,`option_name`,`option_price`) VALUES ('HS1','/images/option/HS1.png',1,'현대 스마트센스 Ⅰ',940000)
INSERT INTO `Option` (`option_code`,`option_image_path`,`option_name`,`option_price`,`option_type_id`) VALUES ('EXD','/images/option/EXD.png','익스테리어 디자인',450000,1)
INSERT INTO `Option` (`option_code`,`option_name`,`option_type_id`,`option_image_path`,`option_price`) VALUES ('SRF','선루프',1,'/images/option/SRF.png',450000)
INSERT INTO `Option` (`option_image_path`,`option_type_id`,`option_price`,`option_code`,`option_name`) VALUES ('/images/option/PAP.png',1,1290000,'PAP','파킹 어시스트 플러스')
INSERT INTO `Option` (`option_type_id`,`option_code`,`option_price`,`option_image_path`,`option_name`) VALUES (1,'CM1',1140000,'/images/option/CM1.png','컴포트 Ⅰ')
INSERT INTO `Option` (`option_code`,`option_price`,`option_image_path`,`option_type_id`,`option_name`) VALUES ('CM2',990000,'/images/option/CM2.png',1,'컴포트 Ⅱ')
INSERT INTO `Option` (`option_image_path`,`option_type_id`,`option_price`,`option_name`,`option_code`) VALUES ('/images/option/AT2.png',1,300000,'17인치 알로이 휠 & 타이어 Ⅱ','AT2')
INSERT INTO `Option` (`option_price`,`option_image_path`,`option_type_id`,`option_name`,`option_code`) VALUES (690000,'/images/option/BIC.png',1,'빌트인 캠(보조배터리 포함)','BIC')
INSERT INTO `Option` (`option_price`,`option_image_path`,`option_code`,`option_type_id`,`option_name`) VALUES (150000,'/images/option/SGI.png','SGI',1,'세이지 그린 인테리어 컬러')
INSERT INTO `Option` (`option_name`,`option_code`,`option_price`,`option_image_path`,`option_type_id`) VALUES ('멀티미디어 내비 Ⅰ','MN1',1290000,'/images/option/MN1.png',1)
INSERT INTO `Option` (`option_type_id`,`option_name`,`option_image_path`,`option_code`,`option_price`) VALUES (1,'컨비니언스','/images/option/CON.png','CON',540000)
INSERT INTO `Option` (`option_price`,`option_code`,`option_type_id`,`option_name`,`option_image_path`) VALUES (890000,'HSS',1,'현대 스마트센스','/images/option/HSS.png')
INSERT INTO `Option` (`option_code`,`option_price`,`option_type_id`,`option_image_path`,`option_name`) VALUES ('EX1',690000,1,'/images/option/EX1.png','익스테리어 Ⅰ')
INSERT INTO `Option` (`option_code`,`option_type_id`,`option_price`,`option_image_path`,`option_name`) VALUES ('E1P',1,940000,'/images/option/E1P.png','익스테리어 Ⅰ 플러스')
INSERT INTO `Option` (`option_type_id`,`option_price`,`option_image_path`,`option_code`,`option_name`) VALUES (1,1240000,'/images/option/PRL.png','PRL','파노라마 선루프 + 루프랙 + LED 실내등(맵램프,룸램프)')
INSERT INTO `Option` (`option_code`,`option_name`,`option_price`,`option_image_path`,`option_type_id`) VALUES ('HEC','하이패스+ ECM 룸미러',250000,'/images/option/HEC.png',1)
INSERT INTO `Option` (`option_image_path`,`option_name`,`option_price`,`option_type_id`,`option_code`) VALUES ('/images/option/X.png','인테리어디자인 Ⅰ',250000,1,'ID1')
INSERT INTO `Option` (`option_type_id`,`option_code`,`option_image_path`,`option_name`,`option_price`) VALUES (1,'COM','/images/option/COM.png','컴포트',1140000)
INSERT INTO `Option` (`option_image_path`,`option_price`,`option_type_id`,`option_code`,`option_name`) VALUES ('/images/option/BIC2.png',640000,1,'BIC2','빌트인 캠(보조배터리 포함)')
INSERT INTO `Option` (`option_image_path`,`option_price`,`option_name`,`option_type_id`,`option_code`) VALUES ('/images/option/EX2.png',690000,'익스테리어 Ⅱ',1,'EX2')
INSERT INTO `Option` (`option_price`,`option_name`,`option_code`,`option_type_id`,`option_image_path`) VALUES (1140000,'파노라마 선루프 + LED 실내등(맵램프,룸램프)','PSL',1,'/images/option/PSL.png')
INSERT INTO `Option` (`option_price`,`option_name`,`option_type_id`,`option_code`,`option_image_path`) VALUES (590000,'인테리어디자인 Ⅱ',1,'ID2','/images/option/X.png')
INSERT INTO `Option` (`option_name`,`option_price`,`option_type_id`,`option_image_path`,`option_code`) VALUES ('플래티넘 Ⅰ',2230000,1,'/images/option/PL1.png','PL1')
INSERT INTO `Option` (`option_type_id`,`option_price`,`option_image_path`,`option_name`,`option_code`) VALUES (1,2520000,'/images/option/PL2.png','플래티넘 Ⅱ','PL2')
INSERT INTO `Option` (`option_image_path`,`option_price`,`option_name`,`option_type_id`,`option_code`) VALUES ('/images/option/PSF.png',1090000,'파노라마 선루프',1,'PSF')
INSERT INTO `Option` (`option_code`,`option_type_id`,`option_image_path`,`option_name`,`option_price`) VALUES ('AVP',1,'/images/option/X.png','어드벤처패키지',790000)
INSERT INTO `Option` (`option_name`,`option_type_id`,`option_image_path`,`option_code`,`option_price`) VALUES ('플래티넘 Ⅲ',1,'/images/option/PL3.png','PL3',1480000)
INSERT INTO `Option` (`option_price`,`option_type_id`,`option_image_path`,`option_code`,`option_name`) VALUES (1780000,1,'/images/option/PL4.png','PL4','플래티넘 Ⅳ')
INSERT INTO `Option` (`option_code`,`option_type_id`,`option_image_path`,`option_price`,`option_name`) VALUES ('NX0002',2,'/images/option/NX0002.png',320000,'LED 라이팅 패키지 (선루프,
  인스퍼레이션 전용)')
INSERT INTO `Option` (`option_type_id`,`option_price`,`option_name`,`option_image_path`,`option_code`) VALUES (2,120000,'러기지 패키지','/images/option/NX0004.png','NX0004')
INSERT INTO `Option` (`option_image_path`,`option_type_id`,`option_code`,`option_price`,`option_name`) VALUES ('/images/option/NX0003.png',2,'NX0003',400000,'빌트인 공기 청정기')
INSERT INTO `Option` (`option_image_path`,`option_price`,`option_code`,`option_type_id`,`option_name`) VALUES ('/images/option/NX0008.png',340000,'NX0008',2,'사이드스텝')
INSERT INTO `Option` (`option_code`,`option_name`,`option_price`,`option_image_path`,`option_type_id`) VALUES ('NX0009','적외선 무릎 워머',300000,'/images/option/NX0009.png',2)
INSERT INTO `Option` (`option_name`,`option_price`,`option_code`,`option_image_path`,`option_type_id`) VALUES ('프로텍션 매트 패키지',230000,'NX0005','/images/option/NX0005.png',2)
INSERT INTO `Option` (`option_image_path`,`option_name`,`option_price`,`option_code`,`option_type_id`) VALUES ('/images/option/NX3855.png','어드벤처 전용 사이드 스텝',340000,'NX3855',2)
INSERT INTO `Option` (`option_name`,`option_image_path`,`option_type_id`,`option_code`,`option_price`) VALUES ('19인치 매트 블랙 경량휠','/images/option/NX3857.png',3,'NX3857',1140000)
INSERT INTO `Option` (`option_name`,`option_image_path`,`option_type_id`,`option_code`,`option_price`) VALUES ('모노블록 브레이크+19인치 매트 블랙 경량휠 패키지','/images/option/NX3858.png',3,'NX3858',2230000)


INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (1,1)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (2,1)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (3,1)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (1,4)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (5,1)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (4,1)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (2,4)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (3,4)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (4,4)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (4,5)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (2,3)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (2,6)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (2,7)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (8,2)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (2,9)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (10,2)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (2,12)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (14,2)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (3,5)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (5,6)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (7,5)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (8,5)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (5,9)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (5,11)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (5,12)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (14,5)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (3,12)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (3,8)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (3,13)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (14,3)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (6,12)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (8,6)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (6,14)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (22,7)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (7,15)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (16,7)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (17,7)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (7,18)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (19,7)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (20,7)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (7,21)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (7,34)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (7,35)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (37,7)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (38,7)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (7,39)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (7,41)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (7,42)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (10,22)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (15,10)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (10,16)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (17,10)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (10,18)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (10,19)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (10,20)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (10,21)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (34,10)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (35,10)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (37,10)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (38,10)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (39,10)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (10,41)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (10,42)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (13,22)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (13,15)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (13,16)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (17,13)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (18,13)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (19,13)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (20,13)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (21,13)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (34,13)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (35,13)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (13,37)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (13,38)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (39,13)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (41,13)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (13,42)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (16,22)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (15,16)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (16,16)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (17,16)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (16,18)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (16,19)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (16,20)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (21,16)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (16,34)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (35,16)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (16,37)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (38,16)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (16,39)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (41,16)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (16,42)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (8,27)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (8,29)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (17,8)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (8,24)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (8,23)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (25,8)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (8,26)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (34,8)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (35,8)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (37,8)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (8,38)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (39,8)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (36,8)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (41,8)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (8,42)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (11,27)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (29,11)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (11,17)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (11,24)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (11,23)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (25,11)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (26,11)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (34,11)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (35,11)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (37,11)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (11,38)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (39,11)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (36,11)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (11,41)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (42,11)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (27,14)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (28,14)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (14,17)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (24,14)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (23,14)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (25,14)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (14,26)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (34,14)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (14,35)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (14,37)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (14,38)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (14,39)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (36,14)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (14,41)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (42,14)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (27,17)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (17,28)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (17,17)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (24,17)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (23,17)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (25,17)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (17,26)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (34,17)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (35,17)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (37,17)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (38,17)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (17,39)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (17,36)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (41,17)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (17,42)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (31,9)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (30,9)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (24,9)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (33,9)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (9,34)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (35,9)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (9,37)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (9,38)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (39,9)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (9,36)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (9,40)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (9,41)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (9,42)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (12,31)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (30,12)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (12,24)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (33,12)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (34,12)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (12,35)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (37,12)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (12,38)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (39,12)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (12,36)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (12,40)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (41,12)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (42,12)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (15,31)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (30,15)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (15,24)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (32,15)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (15,34)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (15,35)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (15,37)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (38,15)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (39,15)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (36,15)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (15,40)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (41,15)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (42,15)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (31,18)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (30,18)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (18,24)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (32,18)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (34,18)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (35,18)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (18,37)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (18,38)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (18,39)
INSERT INTO `CarModelOption` (`model_id`,`option_id`) VALUES (18,36)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (40,18)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (41,18)
INSERT INTO `CarModelOption` (`option_id`,`model_id`) VALUES (42,18)


INSERT INTO `IntColorOption` (`option_id`,`int_color_id`) VALUES (14,2)
INSERT INTO `IntColorOption` (`option_id`,`int_color_id`) VALUES (27,5)
INSERT INTO `IntColorOption` (`option_id`,`int_color_id`) VALUES (27,6)




INSERT INTO `ActivateOption` (`activate_option_id`,`trim_id`,`option_id`) VALUES (2,1,1)
INSERT INTO `ActivateOption` (`option_id`,`activate_option_id`,`trim_id`) VALUES (31,40,4)
INSERT INTO `ActivateOption` (`option_id`,`activate_option_id`,`trim_id`) VALUES (20,34,2)
INSERT INTO `ActivateOption` (`option_id`,`activate_option_id`,`trim_id`) VALUES (26,34,3)
INSERT INTO `ActivateOption` (`option_id`,`trim_id`,`activate_option_id`) VALUES (30,4,34)
INSERT INTO `ActivateOption` (`trim_id`,`activate_option_id`,`option_id`) VALUES (2,41,19)
INSERT INTO `ActivateOption` (`activate_option_id`,`trim_id`,`option_id`) VALUES (42,2,19)
INSERT INTO `ActivateOption` (`trim_id`,`option_id`,`activate_option_id`) VALUES (3,25,41)
INSERT INTO `ActivateOption` (`trim_id`,`option_id`,`activate_option_id`) VALUES (3,25,42)


INSERT INTO `DeactivateOption` (`option_id`,`deactivate_option_id`) VALUES (15,21)
INSERT INTO `DeactivateOption` (`deactivate_option_id`,`option_id`) VALUES (15,21)
INSERT INTO `DeactivateOption` (`deactivate_option_id`,`option_id`) VALUES (19,18)
INSERT INTO `DeactivateOption` (`deactivate_option_id`,`option_id`) VALUES (18,19)
INSERT INTO `DeactivateOption` (`option_id`,`deactivate_option_id`) VALUES (41,42)
INSERT INTO `DeactivateOption` (`deactivate_option_id`,`option_id`) VALUES (41,42)


INSERT INTO `DeleteOption` (`option_id`,`delete_option_id`) VALUES (31,37)
INSERT INTO `DeleteOption` (`delete_option_id`,`option_id`) VALUES (41,31)
INSERT INTO `DeleteOption` (`option_id`,`delete_option_id`) VALUES (31,42)
