# name: Deploy
# on:
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]

# jobs:
#   build:

#     runs-on: ubuntu-latest

#     steps:
#       - uses: actions/checkout@v3
#       - name: Use Node.js
#         uses: actions/setup-node@v3
#         with:
#           node-version: '18.x'

#       - name: Check Node v
#         run: node -v

#       - name: Install Dependencies
#         run: npm install

#       - name: Build
#         run: npm run build --if-present

#       - name: Generate .env file
#         run: |
#           echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" >> .env
#           echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> .env
#           echo "POSTGRES_DB=${{ secrets.POSTGRES_DB }}" >> .env
#           echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env

#       - name: zip create
#         run: zip -qq -r ./test-build.zip .
#         shell: bash

#       - name: Configure AWS credentials
#         uses: aws-actions/configure-aws-credentials@v1
#         with:
#           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
#           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#           aws-region: ap-northeast-2

#       - name: Upload to S3
#         run: aws s3 cp --region ap-northeast-2 ./test-build.zip s3://mycar-bucket-test/test-build.zip


#       - name: Deploy
#         run: aws deploy create-deployment 
#           --application-name mycar-code-deploy
#           --deployment-config-name CodeDeployDefault.AllAtOnce 
#           --deployment-group-name mycar-server
#           --s3-location bucket=mycar-bucket-test,key=test-build.zip,bundleType=zip
#         # run: aws deploy create-deployment --application-name mycar-code-deploy --deployment-config-name CodeDeployDefault.AllAtOnce --deployment-group-name mycar-server --s3-location bucket=mycar-bucket-test,bundleType=zip
